colmap/colmap

src/ext/PBA/SparseBundleCPU.cpp
Should fix compile problems on Ubuntu Xenial.
=> Explicit namespace for std::isfinite(x)

CMakeLists.txt
This little patch enables to build [COLMAP](https://colmap.github.io/) with shared [**Boost**](http://boost.org) library too without affecting current behaviour. Vast majority of distros ship shared boost library only, perhaps in future this shared mode **may** be considered as default.
* To invoke this mode one can run:
```cmake . -DBOOST_STATIC=OFF```
* Please notice the mandatory extra [-DBOOST_TEST_DYN_LINK](http://stackoverflow.com/questions/7781374/boost-test-linking) flag in this shared mode.
=> Enable BOOST in shared mode (optional).

src/base/reconstruction.cc, src/base/reconstruction.h, src/exe/CMakeLists.txt, src/exe/model_aligner.cc
Loads a list of image names with associated 3D coordinates and computes a similarity transform that aligns the cameras in the model with these control points. Writes out the resulting reconstruction in a directory specified by the user.
This has been tested on the Arts Quad dataset, where a reconstruction computed with Colmap was aligned with the east-north ground truth coordinates of a set of images. In order to facilitate the alignment, the y-coordinate of these ground truth points was set to 0.
=> adds functionality to align a reconstruction to a set of control points

CMakeLists.txt, cmake/CMakeHelper.cmake
building colmap for just using it does not need the test binaries,
so here is an option to turn them off.
Not sure exactly about the default value, maybe off is better than on?
=> added an option to build cmake without building the tests

CMakeLists.txt
Escaping COLMAN_VERSION string causes #53 issue.
_Nvcc command line gets malformed
..we gets this_
`/opt/cuda/bin/nvcc -M -D__CUDACC__ /home/bartus/_src/colmap/src/ext/SiftGPU/ProgramCU.cu -o /home/bartus/_src/colmap/build-old/src/ext/SiftGPU/CMakeFiles/sift_gpu.dir//sift_gpu_generated_ProgramCU.cu.o.NVCC-depend -ccbin /usr/lib/colorgcc/bin/cc -m64 -DCOLMAP_VERSION= -D2.1\" -DOPENMP_ENABLED -DCUDA_ENABLED -DCUDA_SIFTGPU_ENABLED -D_FORCE_INLINES\" -Xcompiler ,\"-msse\",\"-msse2\",\"-msse3\",\"-msse4.1\",\"-msse4.2\",\"-mavx\",\"-Wno-maybe-uninitialized\",\"-fopenmp\",\"-fPIC\",\"-march=core2\",\"-mfpmath=sse\",\"-DWINDOW_PREFER_GLUT\",\"-DSIFTGPU_NO_DEVIL\",\"-O2\",\"-g\",\"-DNDEBUG\",\"-msse\",\"-msse2\",\"-msse3\",\"-msse4.1\",\"-msse4.2\",\"-mavx\" -gencode arch=compute_61,code=sm_61 …
=> Fix cmake>3.6 compilation bug

src/base/reconstruction.cc, src/base/reconstruction.h, src/exe/model_converter.cc, src/ui/main_window.cc
Nvm exported file should include full image path for cameras.
Also whitespace need to be replaced with double quote character, at least this is default behavior of `visual-sfm` on linux system.
#92
=> add nvm export full path to image.

CMakeLists.txt
The bug: If having CUDA < 7.0, Colmap's build files will try to build CUDA-enabled libriaries but Colmap uses std=c++11 with nvcc, which CUDA < 7.0 doesn't handle. This results in a compilation error if the system compiling has CUDA < 7.0.
This PR adds a bit of logic to the main CMakeLists file to detect that we have the minimum CUDA version required for colmap to build with Cuda enabled.
=> Fix cuda version

doc/install.rst
Mac build instructions were missing
``` cd build ```
after
``` mkdir build ```
before running CMAKE
=> Add missing directory change to Mac build instructions.

doc/cli.rst
The documentation advises to use the option "--use_gpu true" or "--use_gpu false", but the *_matcher's have instead as input argument "--SiftMatching.use_gpu".
=> Minor correction of input argument for *_matcher's

doc/format.rst
I think the naming of the files changed, but the documentation was not adjusted until now.
=> Naming changed?

doc/cli.rst
It was not clear to me whether COLMAP could visualize a dense reconstruction obtained via the CLI. I think it does no harm to indicate clearly that COLMAP has this feature. 
Regarding the third point about ``mesh.ply``: There I'm actually not sure if it's not possible. In the doc there is written that the surface normals cannot be visualized, but these are just a "part" of the ``dense_mesher`` output, right? Anyway, COLMAP in my case crashes when I try to load ``mesh.ply``, that's why I wrote it like this.
=> Indicate possibility of dense output visualization

scripts/python/read_model.py, scripts/python/test_read_model.py
Hi Johannes, 
I've noticed that Colmap uses now binary model output files by default. 
I've extended your python script 'read_model' to parse also Colmap's binary model output files. The new binary parsing functions return the same data structures as your text parsing functions.  
I added a script to compare the binary and text parsing results generated from the same reconstruction to verify the correctness of this extension. I've tested the script with Python 2.7.13 and Python 3.5.3.
If you have any further remarks/questions/change requests let me know.
Best regards,
Sebastian
=> Python Script to Parse Colmaps Binary Model Output

scripts/python/read_model.py
`model_name` and `num_params` of `CameraModel` namedtuples in `scripts/python/read_model.py` had not been identical with the ones in `src/base/camera_models.h`, so that sparse reconstruction outputs had not been parsed correctly.
I have corrected `read_model.py` according to `camera_models.h`.
=> Fix CameraModel tuples in read_model.py according to camera_models.h

src/exe/colmap.cc
This fix enables highdpi scaling of the qt widgets for high dpi monitors
=> enable high dpi scaling for qt > 5.6.0

src/ui/dense_reconstruction_widget.cc, src/ui/image_viewer_widget.cc, src/ui/image_viewer_widget.h, src/ui/match_matrix_widget.cc
Enhanced image viewer that automatically expands the image over the whole available display area while keeping the same aspectratio. Also works when the image viewer is resized/maximized.
QLabel usage has been removed and instead a GraphicsView is used. This will allow to later render even the correspondences and feature points as graphicsitems instead of rendering them directly to the pixmap.
I tested it and it works really nice on my system.
=> image viewer enhancement

src/base/image_reader.cc
Because of this bug the principal point of the first camera was always set
to (0, 0). Principal point of every subsequent camera was being set to the
center of the previous image, which could be a problem for input images of
different size.
=> Fix for Issue#365

scripts/python/database.py
Using "db.add_camera(...)" writes currently the parameters as np.float32 to the database file. This causes the following error when opening the database file with colmap: " database.cc:207 Check failed:  num_params == camera.NumParams() (2 vs. 4)" (because database.cc expects double values)
=> Fix bug in python db.add_camera() function

lib/SiftGPU/PyramidCU.cpp
If a image level is skipped due to a limit on the number of features, its feature counter can still contain data from the last image. This can lead to invalid features being returned and in the worst case a heap corruption since the total feature number does not match the sum of features per level.
=> Fix SiftGPU bug with skipped levels.

src/exe/colmap.cc, src/util/string.cc, src/util/string.h, src/util/string_test.cc
I made this small change so that the following folder structure can be supported by rig BA:
```
dataset:
- sub_dataset1:
- left:
- img0001.png
- ...
- right:
- sub_dataset2:
- left:
- right:
...
```
This was previously not possible, because the "sub_dataset" string would prevent image names from matching.
=> Allow partial image prefix for nested subfolder rig BA

lib/SiftGPU/SiftMatch.cpp
According to valgrind, for the allocation in `__matcher = new SiftMatchCU(__max_sift);` in SiftMatch.cpp, the custom new operator overload of SiftMatchGPU seems to be used. It uses malloc() internally. However, in the SiftMatchGPU destructor, the __matcher object is deleted using delete. This means that the malloc is mismatched with delete instead of free.
One possible solution is to use the global new to allocate __matcher, as proposed in this PR. However, I'm not entirely sure what the custom new's purpose is - the reasoning in a header file has something to do with some MSVC compiler flags I am not familiar with, but it seems like it might only be intended for allocation of SiftMatchGPU objects:
```
//overload the new operator because delete operator is virtual
//and it is operating on …
```
=> SiftGPU: Fix mismatched malloc-delete

src/base/image_reader.cc, src/base/image_reader.h, src/feature/extraction.cc, src/feature/extraction.h, src/ui/feature_extraction_widget.cc, src/util/misc.cc, src/util/misc.h, src/util/option_manager.cc
This implements masking of images for feature extraction (by removing extracted features at masked-out image locations). Corresponds to issue #208 (regarding sparse features; does not implement masking for dense reconstruction).
Two new image extraction parameters are introduced:
* ImageReader.mask_path to specify a root directory for per-image masks:
```
// Optional root path to folder which contains image masks. For a given image,
// the corresponding mask must have the same sub-path below this root as the
// image has below image_path. The filename must be equal, aside from the
// added extension .png. For example, for an image image_path/abc/012.jpg, the
// mask would be mask_path/abc/012.jpg.png. No features will be extracted in
// regions where the mask image is black (pixel …
```
=> Implement masking of images in feature extraction

doc/cli.rst
This PR fixes an error in the `delaunay_mesher` command-line example in the documentation.
=> Fix pathname for delaunay_mesher example in CLI docs

src/base/undistortion.cc, src/base/undistortion.h, src/base/undistortion_test.cc, src/exe/colmap.cc
This pull request adds additional mode for undistorting, which might be used with fisheye images.
I've tried to solve the following problems:
* Focal length: previously focal length was copied from original camera; for some camera models (i.e. OPENCV_FISHEYE) focal length parameters are not directly connected with focal length of undistorted camera
* Valid region estimation: frequently fisheye images contain valid image data only in some circular region; moreover, model validity (i.e. monothonicity of distance-to-principal-point and angle-to-optical axis) is not guaranteed outside of this region (due to no data available during calibration)
With `estimate_fov` enabled, field-of-view of undistorted camera is estimated by iteratively testing monotonicity of angle-distance relationship …
=> FOV-based undistortion

src/estimators/generalized_absolute_pose.cc, src/estimators/generalized_absolute_pose.h, src/estimators/generalized_absolute_pose_test.cc
This makes the GP3PEstimator consistent with all other estimators which return the squared distance (and RANSAC using the squared threshold for comparison).
=>  Return squared cosine distance as residuals in GP3PEstimator. 

doc/faq.rst
Hi,
Just found that the FAQ documentation for `patch_match_stereo` was out of date since the options changed from `--DenseStereo.*` to `--PatchMatchStereo.*` (`3.5-dev.2` https://github.com/colmap/colmap/commit/f1ec0beba689d9d725fb2922b8e41913c394baf6).
Tis PR fixes that part of the documentation.
Thanks,
=> Updated documentation for patch_match_stereo CLI options

CMakeLists.txt
The following line in CMakeLists.txt
find_package(CGAL QUIET)
causes problems on my system. What worked is to put it in the conditional: 
if (CGAL_ENABLED)
find_package(CGAL QUIET)
endif()
I think this makes sense. If the user does not want CGAL, why try searching for it to start with. This fixed it.
Here's the error I get.  It is nasty. CGAL itself exists, but a Qt library having CGAL does not exist. 
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/CGAL/CGALExports.cmake:83 (message):
The imported target "CGAL::CGAL_Qt5" references the file
"/usr/lib/x86_64-linux-gnu/libCGAL_Qt5.so.11.0.1"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The …
=> CMakeLists: Do not error out if finding CGAL fails

doc/faq.rst
Corrects FAQ example in _Register/localize new images into an existing reconstruction_ section.
The _colmap image_registrator_ command does not accept the --image_path argument.
=> drop unrecognised option from FAQ example

lib/VLFeat/kmeans.c
Pick up https://github.com/vlfeat/vlfeat/pull/200. See [error log](http://package22.nyi.freebsd.org/data/112amd64-default-PR238330/2019-06-09_20h29m30s/logs/errors/colmap-3.5_7.log).
For `master` branch. I haven't tested `dev` yet.
=> VLFeat: unbreak build with GCC 9

src/base/undistortion.cc, src/base/undistortion.h, src/exe/colmap.cc
Implements functionality to undistort images without a 3D reconstruction by adding a new option to the `colmap` executable: `colmap image_undistorter_standalone`.
Rather than reading the image names and camera parameters from a reconstruction, `colmap image_undistorter_standalone` loads this information from a text file (paramter `--input_file`. Each line in the text file specifies the filename of an image and its camera parameters. Here is an example:
`day_hq/day_hq_00013.jpg SIMPLE_RADIAL_FISHEYE 1280 720 467.338 640 360 0.20964`
=> added functionality to undistort images without the need for a 3D model

src/exe/colmap.cc
When running bundle_adjust cli command, check that specified
--input_path and --output_path directories exist.
This way we get a nice error message right at the start,
instead of getting a more cryptic error message after
potentially lengthy processing.
=> check --input_path and --output_path when running bundle_adjuster command

scripts/matlab/read_model.m
Color values are converted to signed 8bit integer so the range is limited from 0 to 127 (-128 to 127, but negative colors are not used). 
The correct type should be UNSIGNED 8bit integer (uint8) so the range is 0 to 255. 
This code change fixes this behaviour.
=> signed/unsigned int color bug in matlab/read_model

src/mvs/cuda_rotate.h, src/mvs/gpu_mat.h
In the COLMAP MVS code, the current implementation of `GpuMat::Rotate()` does not properly handle `GpuMat` objects for which the row pitch (in bytes) is not a multiple of the matrix data type size. So, this usage of the method:
https://github.com/colmap/colmap/blob/06d546bd9bd285263b285b60de19953bb96f9f13/src/mvs/patch_match_cuda.cu#L1672-L1678
does not work as intended, since the `GpuMatPRNG` matrix value data type (`curandState`) is 48 bytes long, which does not divide evenly into the pitch value returned by the `cudaMallocPitch()` memory allocation for many matrix sizes.
This pull request fixes this bug in `GpuMat::Rotate()`. Similar bugs may exist in other `GpuMat` methods (such as `Transpose()`, `FlipHorizontal()`), but they do not affect COLMAP behavior, and I haven't addressed …
=> Fix bug in GpuMat::Rotate() implementation

CMakeLists.txt
This fixes a linking error observed on Mac OS X High Sierra (brew)
=> fix: add missing target library for OpenMP

doc/faq.rst
This section starts by suggesting the user should create a text file with the cameras, and then run feature detection and matching, then use this text file to get the user cameras. The reality is more complicated. The text file should have image ids that agree with the database created during feature detection and matching. This text is clarifying that.
=> Clarify about image id being the same as in the database

src/feature/sift.cc, src/feature/sift.h, src/feature/sift_test.cc
As noted in [this](https://github.com/colmap/colmap/issues/165) issue, master version of COLMAP use brute force search for pairwise feature matching for both CPU and GPU.
This PR implement ANN search for CPU version of matching.
In my tests, ANN is 6-10 times faster than brute force.
Unfortunately, I could not save dot distance function.
I tried create dot distance function for FLANN:
```cpp
struct ReverseDotDistance {
using ElementType = int;
using ResultType = int;
template <class Iterator1, class Iterator2>
ResultType operator()(Iterator1 a, Iterator2 b, size_t size, ResultType /*worst_dist*/ = -1) const {
ResultType result = ResultType();
for (size_t i = 0; i < size; ++i) {
result -= (*a++) * (*b++);
}
return result;
}
};
```
However, dot distance [can't be use in kdtree forest …
=> flann match

doc/tutorial.rst
This pull request is carved out of https://github.com/colmap/colmap/pull/747 which I will close, because it had too many commits and it was not clear what I meant to change.
The point of this pull request is to update some confusing text. The doc was talking about exporting colmap data, both above and below. Hence the text that colmap needs a GPU does not belong there.
=> Update confusing text

src/ui/main_window.cc
This PR resolves #766 .
Currently, the imported results are potentially incorrect, since `std::stold` etc. depend on the value of `LC_NUMERIC` (see [stof()](https://en.cppreference.com/w/cpp/string/basic_string/stof) ).
Further, I observed that the value of `LC_NUMERIC` within colmap depends on how the corresponding code has been executed (command line vs gui). Concretely, `std::setlocale(LC_NUMERIC, NULL)` returned `C` using the command line (e.g. `colmap bundler_adjuster`) and `de_DE.UTF-8` using the gui (i.e. `colmap gui`). I guess that QT changes this value somewhere. 
Therefore, this PR adjusts the value of `LC_NUMMERIC` at a global gui level. (All functions loaded by the gui are affected and redundancy is avoided).
If you feel that the value should be changed somewhere else just let …
=> Fixed txt parsing error caused by incorrect LC_NUMERIC value

src/CMakeLists.txt
Found [downstream](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=245824). See [error log](https://github.com/colmap/colmap/files/4530640/colmap-3.6.d.3.22.log).
=> Unbreak CGAL_ENABLED with CGAL 5.0

src/base/image_reader.cc
In documentation not required what `image_list`, which contains in `image_list_path` must be sorted. However, in realization this is expected and need for `single_camera_per_folder` mode.
=> force check and sort image_list

lib/PoissonRecon/Geometry.h
Would not compile otherwise with GCC 10.1.0:
```
In file included from /tmp/tmp.ij35ejNwXQ/colmap/lib/PoissonRecon/Geometry.cpp:28:
/tmp/tmp.ij35ejNwXQ/colmap/lib/PoissonRecon/Geometry.h:344:2: error: ‘FILE’ does not name a type
344 |  FILE* _fp;
|  ^~~~
In file included from /tmp/tmp.ij35ejNwXQ/colmap/lib/PoissonRecon/Geometry.cpp:28:
/tmp/tmp.ij35ejNwXQ/colmap/lib/PoissonRecon/Geometry.h:36:1: note: ‘FILE’ is defined in header ‘<cstdio>’; did you forget to ‘#include <cstdio>’?
35 | #include "Hash.h"
+++ |+#include <cstdio>
36 | 
```
Also mentioned in #886.
=> add missing include <stdio.h> to lib/PoissonRecon/Geometry.h

src/util/misc.cc
Firstly, catching a polymorphic type like `std::exception` by value causes
warnings. Secondly, we don't want to accidentally catch `std::bad_alloc`,
we only want to catch the errors potentially generated by `std::stoi`, both
of which derive from `std::invalid_argument`:
https://en.cppreference.com/w/cpp/string/basic_string/stol#Exceptions
=> Catch std::invalid_argument const& instead of std::exception in misc.cc.

src/feature/matching.cc, src/feature/matching.h, src/ui/feature_matching_widget.cc, src/util/option_manager.cc, src/util/option_manager.h
Default value for ImagePairsMatchingOptions.block_size should be the same as the number of image pairs to be matched based on default value of ExhaustiveMatchingOptions.block_size (block_size * (block_size - 1) / 2). Low value of this option decrease potential utilization of hardware resources. Also, utilization can be increased by filtering out non unique image pairs.
=> Custom matching speedup

doc/cli.rst
The missing space seems to prevent reStructuredText from properly rendering the word `images.txt` with code font.
=> Fix a reStructuredText issue

src/base/reconstruction.cc, src/base/reconstruction.h, src/exe/colmap.cc
* Adjusted src/base/reconstruction.cc to import point cloud from std::vector<PlyPoints>
* Adjusted src/exe/colmap.cc to allow saving in colmap format when calling stereo_fusion from command line
See Issue https://github.com/colmap/colmap/issues/738
=> Allow to save fused point cloud in colmap format when using command line

src/estimators/absolute_pose.cc, src/estimators/absolute_pose_test.cc
I was doing some benchmarking with absolute pose solvers and found that COLMAP's implementation of EPnP was returning garbage in roughly 25% of cases. After comparing with the OpenGV implementation I found the problem. I have not done any extensive testing after the fix, but I think it should work better now.
=> Fix for EPnP estimator

src/estimators/essential_matrix.cc, src/estimators/essential_matrix_test.cc
De-normalize before enforcing the internal constraints and update the test accordingly. Fixes #861
=> 8 point algorithm internal contraint fix

src/ui/model_viewer_widget.cc
I needed to make this change anyway in my fork and it looks quite upstreamable so I might as well send you this PR. I hope that this is useful and that I'm not missing some obvious reason why the previous version was implemented like that.
=> BuildImageModel: use std::vector instead of numbered arguments

src/feature/matching.cc, src/feature/matching.h, src/feature/sift.cc
1. Fix bug in sift feature matching, when features cannot be extracted from images lacking texture.
2. Fix bug in sift feature matching, when the number of feature points extracted from an image lacking texture is less than 2.
=> Fix bugs of sift feature matching

src/base/camera_database.cc
The return value of StringReplace was not being used and therefore the query was done with the name still containing spaces and dashes.
=> fix camera model query

src/ui/movie_grabber_widget.cc
QT foreach is on deprecation path (https://codereview.qt-project.org/c/qt/qtbase/+/147363) and already may not be available in qt depending on build configuration.
Change to C++11+ range for should be forward-compatible, and as far as I can see C++11 is the current minimum version
=> Remove deprecated qt foreach

src/ui/line_painter.cc, src/ui/point_painter.cc, src/ui/triangle_painter.cc
Throughout the lifetime of the COLMAP software, users on the Windows platform with AMD display drivers have reported problems visualizing 3D geometry in the main display window of the COLMAP GUI. See for example:
- #218 Reconstruction on AMD cards yields wrong results
- #865 Sparse reconstruction show is not normal when I use amd r5 3500u
- [Discussion thread on COLMAP Google Groups](https://groups.google.com/g/colmap/c/pvSB8SxZ3b4)
The source of these problems is an OpenGL programming bug resulting in mismatched vertex attribute indices (locations) between the shader code and the calling code. For example, this current COLMAP code:
https://github.com/colmap/colmap/blob/0aea04cbd9bc5042a70beb5618cd1e52977e13ac/src/ui/line_painter.cc#L84-L92
sets the vertex position attribute to correspond …
=> Fix AMD/Windows GUI visualization bug

src/optim/bundle_adjustment.cc
The Ceres built-in variable `sparse_linear_algebra_library_type ` is set correctly during build, so checking the existence of sparse support before using the `SPARSE_SCHUR` method avoids a runtime crash in bundle adjustment
=> Fix runtime crash when sparsesuite is missing from ceres

scripts/python/database.py, src/base/database.cc, src/base/database_test.cc
Small change to persist two view geometry relative pose (`qvec` and `tvec`) in the corresponding `two_view_geometries` table.
COLMAP's database has a `two_view_geometries` table which serializes instances of the `TwoViewGeometry` class, but it doesn't store the relative pose, which adds the burden of having to re-compute after reading from the database.
Also extended `base/database_test` to test the read and write.
=> Store relative poses in two_view_geometry table

src/base/similarity_transform.cc, src/base/similarity_transform.h
This new functionality can be leveraged when aligning reconstruction if we would rather not estimate a scale factor.
=> Add scale template flag in SimilarityTransform3::Estimate

src/controllers/incremental_mapper.cc, src/controllers/incremental_mapper.h, src/exe/colmap.cc, src/util/option_manager.cc
Incremental mapper now exposes the function tolerance option for local and global BA. This allows for control over the BA convergence by explicitly setting this option when using `mapper` or `hierarchical_mapper`
=> Expose BA options in IncrementalMapper

src/mvs/model.cc, src/mvs/model.h
Instead of using hard-coded values for the sparse and images folders of the model we allow these to be passed as parameters; the default values are compatible with existing functionality.
=> Allow configurable paths for mvs::Model

src/base/reconstruction_manager.cc
ReconstructionManager::Write now uses the NumPoints3D as proxy for a reconstruction's size and writes the output in descending order based on size. This allows larger reconstructions to be written first which is a useful behavior since sparse models may end up with a large main recon and more much smaller ones, and with this change we ensure that if we only look at the first recon it will be the "main" one.
=> Change ReconstructionMaanger to write larger recons first

CMakeLists.txt, src/base/camera_rig.cc, src/base/camera_rig.h, src/exe/colmap.cc
The rig config can now support fields for relative extrinsics and use these values instead of estimating relative poses from the reconstruction. To use the new behavior the rig config must contain the new "location" and "orientation" properties and the flag estimate_rig_relative_poses must be false (`--estimate_rig_relative_poses 0`) when calling `rig_bundle_adjuster`
=> Add fixed extrinsics in rig config

src/exe/colmap.cc, src/mvs/patch_match.cc, src/mvs/patch_match.h, src/util/option_manager.cc
`patch_match_stereo` can now use a custom config using the `--config_path` option instead of just relying on the default `patch-match.cfg` from the workspace. Also a new option for patch-match is introduced (`--PatchMatchStereo.allow_missing_files`) to allow the process to ignore missing source images or depth/normal maps and simply exclude that image index from the patch-match problem without error.
=> Allow custom config and missing dependencies for patch-match

src/base/database.cc, src/base/database.h, src/base/database_test.cc, src/exe/colmap.cc
Added functionality to clear SQLite tables and also call `VACUUM` on `Database::Close` to reduce the DB file size after cleanup.
=> Allow cleanup of SQLite tables using new database_cleaner command

src/base/reconstruction.cc, src/base/reconstruction.h, src/exe/colmap.cc
- model_converter changes:
- Added support for 2 new formats (CAM and Recon3D)
- New option `remove_image_prefix` allows de-registering of images before conversion
- New option `skip_distortion` can be used to export the model without the distortion parameters (set to 0)
=> Support more formats in model_converter

lib/SiftGPU/ProgramCU.cu
With the latest MSVC update the build breaks on Windows with this error:
`error: calling a __host__ function("__floorf") from a __global__ function(...) is not allowed`
This happens due to the use of `floor` reverting to a host function for float arguments, whereas the correct usage of `floorf` is calling a device function.
=> Update SiftGPU to use floorf for floats

src/base/reconstruction.cc
This PR improves the code for some of the model_converter export formats:
1. Fix bugs introduced in PR #1147 affecting the export of Cam and Recon3D formats
2. Add support for non-square pixels to the Cam format exporter
3. Consistently support pinhole camera models for NVM, Cam, Recon3D, and Bundler exporters
=> Improvements to NVM, Cam, Recon3D, and Bundler exporters

src/base/reconstruction.cc
The radial distortion parameters exported by the *.cam file format exporter are currently not computed properly. This PR fixes the `Reconstruction::ExportCam()` exporter so that the radial distortion parameters in *.cam files will accurately reflect the same distortion as in COLMAP.
If both of the two exported radial distortion parameters in a *.cam file are non-zero, then they are used in a distortion model very similar to the COLMAP and Bundler distortion models. However, if only the second parameter is non-zero, then a different camera model (similar to VisualSFM) is assumed for *.cam files.
=> Fix radial distortion in Cam format exporter

scripts/python/build.py
urllib.request.urlretrieve cannot download eigen from gitlab as mentioned in #973 .
This pull request solves this problem by using the requests library, but you need to install a third-party library requests in python 3 .
Before run build.py script, install requests by pip($ python -m pip install requests).
[Installing Requests](https://pypi.org/project/requests/)
=> Fix error of using urllib to download eigen from gitlab

src/util/option_manager.cc
The visibility_sigma variable seemed to have been forgotten for the cli.
=> added visibility_sigma to CLI input options for delaunay_mesher.

src/exe/model.cc
In previous versions of Colmap, the `model_aligner` would align a 3D model to a set of camera poses. In this version, not setting the `alignment_type` option defaults to aligning the model with the dominant plane, which is not the behavior users would expect given previous versions (see #1239 ). I suggest to keep backwards compatibility by keeping the original behavior as the default.
=> Backwards compatibility of model_aligner

src/estimators/generalized_absolute_pose.cc, src/estimators/generalized_absolute_pose.h, src/estimators/generalized_absolute_pose_test.cc
Currently the generalized absolute pose solver computes the squared cosine similarity:
https://github.com/colmap/colmap/blob/cf4a39cee879a1c1000bac7f92cdc024c4c4c523/src/estimators/generalized_absolute_pose.cc#L319-L321
This is not consistent with the single-camera solver, which uses the squared reprojection error, and makes it tricky to tune the RANSAC inlier threshold. This PR allows the GP3P solver to optionally instead compute the reprojection error.
Catch: in-class initialization of non-static data members requires C++>=11, but afaik COLMAP already assumed C++11.
@mihaidusmanu @ahojnnes @mgprt
=> Compute reprojection error in generalized absolute solver

docker/Dockerfile, docker/README.md
Current docker/build.sh failed because git needs tzdata, and tzdata asked to select geographic area, but it accidentally stops. 
So I fixed it.
=> revise Dockerfile and readme.

src/exe/feature.cc
Allows users to select between L1_ROOT and L2 at runtime in the feature_extractor (for benchmarking purposes). Default stays RootSIFT as it usually performs better.
=> Added descriptor normalization argument to feature_extractor.

src/util/cuda.cc
Otherwise if there's an error `GetNumCudaDevices` returns uninitialized memory.
=> Add CUDA_SAFE_CALL to cudaGetDeviceCount.

src/optim/ransac.h
This was observed to lead to a SIGILL error. It could be due to num_inliers being zero, or that inlier_ration ^ kMinNumSamples being so small, that it flushes to zero.
=> Prevent a divide by zero corner case.

cmake/CMakeConfig.cmake.in
PR https://github.com/colmap/colmap/pull/1165 introduced the CMake option `GUI_ENABLED` to disable to GUI but did not disable the Qt requirement in the exported `COLMAPConfig.cmake` file.
=> Require Qt in COLMAPConfig only if GUI is enabled

src/base/reconstruction.cc, src/exe/feature.cc
When writing variables to std::ostringstream, we will loose precision of double variables if output manipulators were not applied.
=> Keep precision in the process of storing in text.

src/exe/feature.cc, src/exe/feature.h, src/exe/sfm.cc, src/exe/sfm.h
In pycolmap we now bind some of the exe functions like RunPointTriangulator. See [pycolmap/pipeline.cc](https://github.com/colmap/pycolmap/blob/master/pipeline.cc). We therefore need COLMAP to expose some exe code that is currently hidden in anonymous namespace or argc-argv functions. Most of this code is likely useful for others and worthy to be publicly exposed, but src/exe is probably not the right place for it.
Any advice on where these bits should be moved?
@ahojnnes @mihaidusmanu @Phil26AT
=> Expose exe internals

src/estimators/two_view_geometry.cc
Currently, the inliers found with the fundamental matrix are always the one used in EstimateUncalibrated(), even if the homography is selected as a better fit.  This commit fixes this behavior.
=> Fix inliers matches extraction in EstimateUncalibrated function.

src/exe/CMakeLists.txt
PR https://github.com/colmap/colmap/pull/1366 exposed some functions in src/exe but I forgot to include these files in the exported library.
=>  Expose exe internals - fix

src/base/database.cc, src/base/database.h
Fix for #1413 . Vacuum command was applied whenever the close function is called leading to important delay whenever accessing the database.  As the vacuum command is meant to decrease the size of db files by deleting allocated chunks of memory not used anymore, the PR only applies it when elements are deleted from the database.
=> Only apply sqlite vacuum command when elements are deleted from the database.

src/util/random.cc, src/util/random.h
this will allow set random seed from external interface, like:
`--random_seed 10`
otherwise, random seed will always be defaulted value.
=> fix random seed set failed from external interface

src/exe/model.cc
Hi team, 
Small change proposed which allows COLMAP to be built from source on the most recent versions of Eigen.
Removal of nonZeros() call which was deprecated in https://gitlab.com/libeigen/eigen/-/commit/08da52eb8537107e2853452bb13c369856d1f84a corresponding to a redundant function call to size().
Issue: COLMAP does not build on Eigen 3.4.90 (and presumably sub-releases since above commit).
Fix: Adjust nonZeros() call to be size().
This is a somewhat interesting issue, because if COLMAP intends to check the number of non-zero elements, the original implementation seemingly did not do that. If the intention was indeed to check non-zero elements a custom check of the matrices is needed pending an appropriate fix in Eigen.
More details on the Eigen front here: …
=> Replace deprecated Eigen nonZeros() call for most recent Eigen versions.

docker/Dockerfile
This PR fixes the following issue when trying to build the docker image:
```
./build.sh 
Sending build context to Docker daemon  239.6kB
Step 1/8 : FROM nvidia/cuda:11.6.0-devel-ubuntu20.04
---> 88f06c9c4dd4
Step 2/8 : ENV DEBIAN_FRONTEND=noninteractive
---> Using cache
---> e642ae3f706b
Step 3/8 : RUN apt-get update && apt-get install -y     git     cmake     build-essential     libboost-program-options-dev     libboost-filesystem-dev     libboost-graph-dev     libboost-system-dev     libboost-test-dev     libeigen3-dev     libsuitesparse-dev     libfreeimage-dev     libmetis-dev     libgoogle-glog-dev     libgflags-dev     libglew-dev     qtbase5-dev     libqt5opengl5-dev     libcgal-dev
---> Using cache
---> a77a22ace47f
Step 4/8 : RUN apt-get -y install     libatlas-base-dev …
```
=> Fix ceres-solver folder name

src/feature/extraction.cc, src/feature/matching.cc, src/mvs/meshing.cc, src/util/threading.h
Features in this PR:
- Support move constructor when calling Push of JobQueue.
- Avoid copy constructor when calling Pop of JobQueue.
Using the above features, we can avoid calling the copy constructor/assignment in tasks such as feature extraction/machining or meshing.
=> Avoid the calling of copy constructor/assignment

src/feature/matching.cc, src/feature/matching.h
Use std::shared_ptr in LRUCache for FeatureKeypoints and FeatureDescriptors.
Avoid (or reduce) calling copy constructors of FeatureKeypoints and FeatureDescriptors when accessing FeatureKeypoints and FeatureDescriptors.
=> Avoid calling copy constructors of  FeatureKeypoints and FeatureDescriptors

src/estimators/pose.cc
Ceres hard crashes (`LOG(FATAL)`) in `covariance.GetCovarianceMatrixInTangentSpace` if the Jacobian matrix is rank deficient. In this case, `covariance.Compute` returns `false` as well. 
If the Jacobian computation fails, we can directly return false (refinement failed) to avoid the hard crash.
=> Avoid hard crash if Jacobian matrix is rank deficient

src/controllers/automatic_reconstruction.cc
In current AutomaticReconstructionController implementation, the cli args input are first parsed to construct the member variable `options_` of `AutomaticReconstructionController` class. 
Then the `options_`'s _ImageReader_ part is assigned to ` ImageReaderOptions reader_options`, which is a copy instead of a reference of `*option_manager_.image_reader`. Which means, user cli args input's _ImageReader_  setting (e.g. single_camera, camera_model) are only passed to `options_`, and will not be synced to `option_manager_`.
Although the ImageReaderOptions setting `reader_options` is used to construct the `SiftFeatureExtractor`, the executed setting is exactly what the user needed. Because the project.ini writing only follows the `option_manager_`'s values, thus when user modify the default …
=> Fix inconsistent between the actual executed image reader option and the saved project.ini file

docker/Dockerfile
There is no `--tag` option for `git clone` only `--branch` [1]. What is happening is git seems to be ignoring the `--tag` flag and naming the clone 2.1.0. But it is *not* checking out that version. It checks out master. 
[1] https://git-scm.com/docs/git-clone
=> checkout the expected version of ceres solver

src/ui/dense_reconstruction_widget.cc
Adds use_cache option in stereo_fusion options GUI (previously only available through command line interface)
=> Add use_cache in fusion options GUI

.azure-pipelines/build-ubuntu.yaml, .azure-pipelines/build.yaml, src/util/threading.h
Azure pipelines deprecated 18.04 in favor of introducing 22.04.
=> Add CI pipeline for Ubuntu 22.04

src/base/database_cache.cc, src/base/database_cache.h, src/base/point3d.h, src/base/reconstruction.cc, src/base/reconstruction.h, src/base/track.h, src/sfm/incremental_mapper.cc, src/sfm/incremental_triangulator.cc
Better usage of move semantics to avoid unnecessary and expensive copy of data.
=> Avoid unnecessary copies of data

CMakeLists.txt
Using find_package resulted in missing CUDA::cudart, CUDA::cublas, etc, from my machine.
WSL Ubuntu 20, CMake 3.24, CUDA 12.
Using find_package(CUDAToolkit) solved this issue. Also, FindCUDA is departed since CMake 3.10!
Have not tested this in other machines and new to using CUDA, so maybe this might be a wrong approach to this problem...
references:
https://cmake.org/cmake/help/latest/module/FindCUDA.html
https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html
=> Use FindCUDAToolkit when available.

src/base/undistortion.cc
When distortion coefficients are really small but not zero, IsUndistorted() may return true, but undistorted image size may still be different from the original image size. In this situation the mismatch between the image size in the model and the actual image size causes the patch match stereo step to crash. This change skips camera undistortion when the coefficients are very small, which makes it consistent with image undistortion and fixes the crash.
=> Fixed a crash due to inconsistent undistortion

docker/Dockerfile
The libmetis-dev  is installed from line 19. Delete the redundancy install of libmetis-dev at line 26.
=> Delete the redundancy install of libmetis-dev

src/base/image_reader.cc, src/util/misc.cc, src/util/misc.h
OS: macOS 12.5.1
COLMAP version: 3.8
I experienced the problem that my image masks where not used during feature extraction. Debugging of the mask loading process showed that function `GetRelativePath(options_.image_path, image_path)` had a faulty behaviour:
- Inputs (example):
- options_.image_path: /users/buesma/colmap-ws/images/
- image_path: /users/buesma/colmap-ws/images/cam1/image0001
- Retval (expected): cam1/image0001
- Retval (actual): ../cam1/image0001
This could be related to issues of the BOOST filesystem library with paths with trailing slashs under macOS (probably related boostorg/filesystem#76). The wrong path lead to `ExistsFile(mask_path)`returning `False`, and therefore to not loading the image mask.
As `options_.image_path` is fully contained in `image_path`, the (for …
=> Fix broken loading of image masks on macOS

doc/cli.rst
Corrected the reference to the `automatic_reconstructor` command under the "Commands" heading.
=> Fix typo in cli.rst

src/feature/sift.cc
**This is an important fix which could improves reconstruction quality in many cases.**
Fix the issue of inconsistent resize behavior between CPU version of SIFT and siftGPU.
The 'max_image_size' is passed to '-maxd' flag of siftGPU. The '-maxd' flag means _maximum working dimension of SIFT algorithm_. The problem is that the _maximum working dimension of SIFT algorithm_ is twice the maximum of the image width/height(The SIFT algorithm first doubles the width and height of its input image).
The issue will cause that many reconstructions which used siftGPU features suffer from potentially lower feature quality and less feature numbers due to unexpected image down-sampling.
Check siftGPU manual for more details.
=> Fix inconsistent image resizing between CPU/GPU implementations of SIFT

src/base/camera_models.h
The description of the model was accidentally duplicated from the model above.
=> Fixed mistake in code comment for OpenCV Fisheye camera

src/mvs/mat.h
Some of the CHECK statements in Mat::Read() do not log the name of the file that triggers them. This can cause crashes that are difficult to debug.
=> Log the name of the file that causes Mat::Read() to checkfail

src/util/ply.cc
When reading a ply file, it seems properties x,y,z should exist in the header. Correct checking "z" property is missing or not.
=> check Z_index correctly in ReadPly

src/mvs/mat.h
The previous version opens the matrix file in text mode, reads or writes the header, then re-opens the file in binary mode to read or write the data. This can cause issues on some network filesystems that do not guarantee immediate availability of the file after it is initially written. On such filesystems the Write() method may not see the file after writing the header, which results in overwriting the header instead of appending to it.
After this change the file is opened only once using binary mode. This is OK because the header does not contain any newline characters or non-ASCII characters.
=> Don't re-open files when reading and writing matrices

src/colmap/base/cost_functions.h
In #1477, checks of the Ceres version were added to choose between the newer ceres::Manifold or the deprecated ceres::LocalParameterization interface, e.g.:
https://github.com/colmap/colmap/blob/bce8f13727960d9aa4a21bc87524ed11f4706f4f/src/colmap/base/cost_functions.h#L298
However, this test will incorrectly return False for Ceres versions 3.0, 4.0, etc. This PR fixes this bug so that True is returned for all Ceres versions 2.1 and beyond.
=> Fix Ceres version test

src/colmap/sfm/incremental_mapper.cc
the latest logic will always use the new coming image observed 3D points, this is not shared.
Related issue: https://github.com/colmap/colmap/issues/1953
@ahojnnes could you help double check? thanks~
=> [Bug] fix finding shared points3D in FindLocalBundle

src/colmap/exe/model.cc
When solving the issue, I found the model analyzer didn't print model detail, I add an option to print the detail camera and image information. I think it's useful tooling enhancement.
https://github.com/colmap/colmap/issues/1946
would continue follow up the issue.
=> [feature] print verbose information for model analyzer

src/colmap/base/database.cc
- Add a missing include to compile with gcc13 on Fedora 38
=> Add a missing include to compile with gcc13

src/colmap/optim/sampler.h
Any superclass that has virtual methods should also have a virtual destructor, otherwise there's a risk of undefined behavior (if an object of a subclass is deleted through a pointer to the superclass).
=> Added a virtual destructor to Sampler

cmake/CMakeConfig.cmake.in
Breaking changes introduced by https://github.com/colmap/colmap/pull/2016 and https://github.com/colmap/colmap/pull/2017.
=> Add missing Boost::graph import

CMakeLists.txt, cmake/CMakeConfig.cmake.in
I'm on Ubuntu 18.04 and seeing the extra `-fPIC` flag added by Qt 5.9.5, as reported in https://github.com/colmap/colmap/issues/1753 https://github.com/colmap/colmap/issues/1813. Upgrading to cmake 3.26 does not help. I think that it's safer to remove the flag regardless of the Qt version.
=> Remove check on Qt version

src/colmap/base/cost_functions.h, src/colmap/base/cost_functions_test.cc
Since all points in an image share a pose, we can use the reference of Rigid3d in BundleAdjustmentConstantPoseCostFunction to avoid memory consumption.
=> Use the reference of Rigid3d to reduce memory consumption

src/colmap/estimators/cost_functions.h, src/colmap/estimators/cost_functions_test.cc, src/colmap/estimators/pose.cc
Add a new costfunction-ReprojErrorConstantPoint3DCostFunction  to speed up the RefineAbsolutePose function.
=> Add ReprojErrorConstantPoint3DCostFunction to speed up the RefineAbsolutePose function

src/colmap/util/CMakeLists.txt
Conditionally add the files `testing.h` and `testing.cc` to the library target `colmap_util` only if `TESTS_ENABLED=ON`.
Otherwise one needs the `gtest/gtest.h` header available, for example by installing the Debian package `libgtest-dev`, even though no tests are actually built.
Using the `target_sources()` function (Introduced with CMake 3.1`) to conditionally add the two testing files to the util target.
https://cmake.org/cmake/help/latest/command/target_sources.html
Fixes: https://github.com/colmap/colmap/issues/2101
=> cmake: add testing.cc to colmap_util only if TESTS_ENABLED=ON

doc/install.rst
Not sure if this is actually correct, but the `dev` branch doesn't exist anymore, and [this](https://github.com/colmap/colmap/commit/58ba46f81db47e2982545f763698f312d793e9e3) commit seems to suggest that it's formally no longer being used.
=> Update Linux install documentation with new branch policy

doc/cameras.rst
the header file is now in sensor and not in camera anymore
=> Fix link in camera model documentation

CMakeLists.txt, doc/install.rst, src/colmap/exe/CMakeLists.txt, src/colmap/exe/feature.cc, src/colmap/exe/feature.h, src/colmap/exe/model.cc, src/colmap/exe/model.h
- Rename the executable target `colmap_exe` -> `colmap_main`.
- Add lib target `colmap_exe` to expose some internals of exe/{feature,sfm} for pycolmap - done in https://github.com/colmap/colmap/pull/1368 but the target was deleted in a recent commit.
- Expose the internals of RunModelComparer
=> Expose exe as libs

src/colmap/estimators/CMakeLists.txt, src/colmap/estimators/alignment.cc, src/colmap/estimators/coordinate_frame_test.cc, src/colmap/estimators/essential_matrix_test.cc, src/colmap/estimators/generalized_absolute_pose.cc, src/colmap/estimators/generalized_absolute_pose_test.cc, src/colmap/estimators/generalized_relative_pose.cc, src/colmap/estimators/generalized_relative_pose_test.cc, src/colmap/estimators/homography_matrix.cc, src/colmap/estimators/similarity_transform.h, src/colmap/estimators/similarity_transform_test.cc, src/colmap/estimators/two_view_geometry.cc, src/colmap/exe/sfm.cc, src/colmap/geometry/CMakeLists.txt, src/colmap/geometry/essential_matrix_test.cc, src/colmap/geometry/pose_test.cc, src/colmap/geometry/sim3.cc, src/colmap/geometry/sim3.h, src/colmap/geometry/sim3_test.cc, src/colmap/retrieval/CMakeLists.txt, src/colmap/scene/reconstruction.cc
Nasty dependency cycle:
```
"colmap_estimators" of type STATIC_LIBRARY
depends on "colmap_geometry" (weak)
depends on "colmap_image" (weak)
depends on "colmap_scene" (weak)
"colmap_geometry" of type STATIC_LIBRARY
depends on "colmap_estimators" (weak)
depends on "colmap_image" (weak)
depends on "colmap_scene" (weak)
"colmap_image" of type STATIC_LIBRARY
depends on "colmap_scene" (weak)
depends on "colmap_geometry" (weak)
depends on "colmap_estimators" (weak)
"colmap_scene" of type STATIC_LIBRARY
depends on "colmap_geometry" (weak)
depends on "colmap_estimators" (weak)
depends on "colmap_image" (weak)
```
Options:
1. Move `SimilarityTransform` to geometry
2. Move `Sim3d::Estimate` to `similarity_transform.h`
In the end I went for 2.
=> Clean up dependencies

src/colmap/feature/CMakeLists.txt, src/colmap/feature/sift.cc
Since https://github.com/colmap/colmap/pull/2176, building with `CUDA_ENABLED=ON GUI_ENABLED=OFF` fails due to undfined `GL_*` symbols:
https://github.com/colmap/colmap/blob/e7014366d750ba5a7e05956bc16617af84588cbd/src/colmap/feature/sift.cc#L652-L656
=> Restore GLEW include

src/colmap/ui/reconstruction_manager_widget.cc
For some datasets with less overlap, small reconstructions will be merged into larger reconstruction or deleted. At this point, colmap may throw an exception if small reconstructions are selected on the ui. This PR attempts to fix this problem.
=> Fix bug in ReconstructionManagerWidget::Update

src/colmap/ui/project_widget.cc
This PR fixes typos in **project_widget.cc** file.
Following typos have been fixed:
`databse` -> `database`
No other changes.
=> fix: typo in colmap/src/colmap/ui/project_widget.cc

src/colmap/CMakeLists.txt, src/thirdparty/PoissonRecon/CMakeLists.txt
Commit 717d069 does now enforce C++14 in any case.
@ahojnnes This is basically a revert of commit 3a2ae37 and commit 2bc8182.
If compilation with compilers not supporting C++14 might still work, removing the `CMAKE_CXX_STANDARD_REQUIRED` added in commit 717d069 would automatically downgrade to the highest C++ version supported by the compiler.
=> Stop setting C++ standard flags manually

src/colmap/util/threading.h
`std::result_of` is being deprecated in C++17 and removed in C++20 https://en.cppreference.com/w/cpp/types/result_of
=> Replace result_of with invoke_result_t

src/colmap/image/undistortion.cc, src/colmap/scene/camera.h, src/colmap/scene/camera_test.cc, src/colmap/scene/reconstruction.cc
Simplify the higher level logic, especially for Python users (https://github.com/colmap/pycolmap/issues/199).
By the way: what is the rationale for using debug checks `DCHECK_*` instead of `CHECK_*` in `scene/camera.h` getters and setters?
=> Allow getters FocalLength{X,Y} for isotropic models

src/colmap/controllers/incremental_mapper.h
Hiding `IncrementalMapperOptions::{mapper,triangulation}` seems unnecessary and prevents us from binding their options.
=> Expose IncrementalMapperOptions::{mapper,triangulation}

doc/install.rst
Based on build pipeline
https://github.com/colmap/colmap/blob/main/.azure-pipelines/build-mac.yaml
Adresses https://github.com/colmap/colmap/issues/2253
=> Update install instructions for Mac

src/colmap/util/version.cc.in
This PR is probably trivial and won't affect performance.
Since COLMAP_VERSION, COLMAP_COMMIT_ID, COLMAP_COMMIT_DATE, etc. are all string constants, there is no need to use std::string.
=> Replace std::string with constant chars

src/colmap/mvs/fusion.cc, src/colmap/sensor/CMakeLists.txt, src/colmap/sensor/bitmap.cc, src/colmap/sensor/bitmap.h, src/colmap/sensor/bitmap_test.cc
This avoids propagating the FreeImage target to other libraries, as it is now defined as a private link library. As a side effect, this circumvents a bug in CMake, as FreeImage defines /EHsc flags as a public compiler flag that is not correctly propagated by CMake to the nvcc.
=> Fully encapsulate freeimage in bitmap library

doc/install.rst
When CMAKE_BUILD_TYPE is not specified, cmake links the debug version of the dependencies(not all) by default.
Maybe it's a problem with vcpkg。
CMakeCache.txt without specifying building type.
```
//Path to a library.
BLAS_openblas_LIBRARY:FILEPATH=F:/Libs/vcpkg/vcpkg/installed/x64-windows/debug/lib/openblas.lib
//Build the testing tree.
BUILD_TESTING:BOOL=OFF
//Activate the debug messages of the script FindBoost
Boost_DEBUG:BOOL=OFF
//Boost filesystem library (debug)
Boost_FILESYSTEM_LIBRARY_DEBUG:FILEPATH=F:/Libs/vcpkg/vcpkg/installed/x64-windows/debug/lib/boost_filesystem-vc140-mt-gd.lib
//Boost filesystem library (release)
Boost_FILESYSTEM_LIBRARY_RELEASE:FILEPATH=F:/Libs/vcpkg/vcpkg/installed/x64-windows/lib/boost_filesystem-vc140-mt.lib
//Boost graph library (debug) …
```
=> Link against the release version dependencies when building with vcpkg

src/colmap/image/line.cc, src/colmap/mvs/workspace.h
Fix:
```
/home/conda/feedstock_root/build_artifacts/colmap_1704738145804/work/src/colmap/image/line.cc: In function 'std::vector<colmap::LineSegment> colmap::DetectLineSegments(const colmap::Bitmap&, double)': /home/conda/feedstock_root/build_artifacts/colmap_1704738145804/work/src/colmap/image/line.cc:63:8: error: 'unique_ptr' is not a member of 'std'
63 |   std::unique_ptr<double, RawDeleter> segments_data(
|        ^~~~~~~~~~
/home/conda/feedstock_root/build_artifacts/colmap_1704738145804/work/src/colmap/image/line.cc:36:1: note: 'std::unique_ptr' is defined in header '<memory>'; did you forget to '#include <memory>'?
```
=> Add missing "include <memory>" needed for unique_ptr

scripts/python/read_write_model.py
This fixes an issue where read_images_binary() throws an exception when decoding image names with multi-byte characters.
UTF-8 encodes characters using one to four bytes, so decoding byte-by-byte sometimes won't work if a character is encoded with more than one byte. For instance, if a character is encoded using three bytes, all three bytes need to be passed into `.decode("utf-8")` for it to return the proper character. This pull request decodes the entire image name at once to avoid this issue.
=> Support decoding multi-byte characters in Python script

docker/Dockerfile
Splitting the Dockerfile in two stages reduces the size of the final image considerably, since all the build dependencies are not needed.
You can still create the tag for the stages separately:
```bash
docker build --target builder -t colmap:builder .
docker build --target runtime -t colmap:runtime .
```
But the default command (without `--target`) is the last stage, so:
```bash
docker build -t colmap:latest .
```
will refer to `--target runtime` because it is the last stage in the Dockerfile.
=> Split Dockerfile in two stages: builder and runtime.

.azure-pipelines/build-windows.yaml
The build of `jasper` is broken, a patch has been recently applied in vcpkg.
=> Update VCPKG commit in Windows CI

src/colmap/estimators/cost_functions.h, src/colmap/estimators/cost_functions_test.cc, src/pycolmap/estimators/bindings.h, src/pycolmap/estimators/cost_functions.h
- Introduces a new `IsotropicNoiseCostFunctionWrapper` to scale the BA cost functions with the covariance of the detection noise - this was needed in LaMAR to optimize camera with very different resolution and will be useful in COLMAP in the future.
- I haven't figured out how to efficiently support a full anisotropic covariance matrix. We don't need it for now so I'll give it a try another time.
- Examples of usage of the pycolmap bindings for BA and PGO: https://github.com/cvg/pyceres/tree/main/examples
- If `pyceres` is not installed, calling any of these function will result in an error - we don't want to make it a hard dependency yet
=> Add cost functions to pycolmap

src/colmap/util/CMakeLists.txt, src/colmap/util/logging.h, src/colmap/util/logging_test.cc, src/colmap/util/sqlite3_utils.h
Vistual Studio 2022 outputs compiler warning C4722.
`warning C4722: 'colmap::LogMessageFatalThrow<std::invalid_argument>::~LogMessageFatalThrow<std::invalid_argument>': destructor never returns, potential memory leak`
This PR attempts to suppress the C4722 warning. But I'm not sure if this is a good idea.
[Compiler Warning (level 1) C4722](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4722?view=msvc-170)
```
'function' : destructor never returns, potential memory leak
The flow of control terminates in a destructor. The thread or the entire program will terminate and allocated resources may not be released. Furthermore, if a destructor will be called for stack unwinding during exception processing, the behavior of executable is undefined. …
```
=> Fix warning C4722

src/colmap/estimators/triangulation.cc, src/colmap/estimators/triangulation.h, src/colmap/sfm/incremental_triangulator.cc, src/pycolmap/estimators/triangulation.h
- Simplify the interface of `EstimateTriangulation` to ease its Python bindings
- Abstract duplicated code in the `IncrementalTriangulator`
=> Simplify the low-level triangulation API

cmake/FindDependencies.cmake, src/colmap/util/logging.h, src/pycolmap/main.cc
- Context: multiple libraries might initialize glog, e.g. pyceres and pycolmap. Initializing glog twice causes a fatal error
- Add a fix for glog >=0.6.0. There exists a (hacky) workaround for 0.4.0 but not for 0.5.0.
- This PR also adds support for glog 0.7.0
=> Initialize glog in pycolmap only if not already done

src/colmap/scene/database.cc, src/colmap/scene/database.h, src/colmap/scene/database_cache.cc, src/colmap/scene/database_test.cc, src/colmap/scene/synthetic.cc, src/colmap/sfm/incremental_triangulator.cc, src/colmap/util/logging.h, src/pycolmap/scene/database.h
Related to this PR: `FeatureKeypoint`/`FeatureKeypoints` and `FeatureMatch`/`FeatureMatches` are not Python-friendly, would it be OK to replace all their occurrences with their blob counterparts? NxD matrices are directly translated to numpy arrays. This would simplify the COLMAP code as well and also make it cleaner to support non-affine features.
=> Improve bindings of Database

.github/workflows/build-ubuntu.yml, src/colmap/controllers/incremental_mapper.cc, src/colmap/controllers/incremental_mapper.h, src/colmap/exe/sfm.cc, src/colmap/exe/sfm.h, src/colmap/sfm/incremental_mapper.cc, src/colmap/sfm/incremental_mapper.h
Major simplification of `IncrementalMapperController:Reconstruct`. This should make it easier to rewrite it in Python (next step). The logical behavior of the function is unchanged.
cc @B1ueber2y
=> Simplify IncrementalMapperController

src/colmap/image/undistortion.cc
Explicitly allocating the undistorted bitmap inside UndistortImage() is unnecessary, since the called WarpImageBetweenCameras() does the same.
Fixes #2519.
=> Avoid duplicate image allocation during undistortion

src/pycolmap/scene/point3D.cc
Need to add ``PYBIND11_MAKE_OPAQUE(Point3DMap)`` in both "reconstruction" and "point3D" to make the conversion correct. Fix for https://github.com/colmap/colmap/pull/2502
cc: @sarlinpe for https://github.com/colmap/colmap/issues/2522
=> Fix reconstruction.points3D

src/colmap/controllers/hierarchical_mapper.cc
Fix a bug described here:
https://github.com/colmap/colmap/issues/2525#issue-2251904473
=> Fix 'std::out_of_range' error when using hierarchical_mapper

src/pycolmap/estimators/two_view_geometry.cc
Needed to make two_view_geometry pickle-able (e.g. to use with python multiprocessing) or to write custom two_view_geometry to database.
=> make two view geometry writable

src/pycolmap/scene/bindings.cc
Fix errors when pass an empty list as a `vector<Point2D>`:
```
pycolmap.Image(points2D=[])
RuntimeError: instance allocation failed: new instance has no pybind11-registered base types
```
```
camera.cam_from_img([])
TypeError: cam_from_img(): incompatible function arguments.
```
cc @B1ueber2y
=> Implicitly convert iterator to ListPoint2D

src/colmap/scene/reconstruction.cc
While investigating the model_splitter issue for the current revision 1f95f3ee74fdbc020ef2dca190ec56958ea5f9e1 described in https://github.com/colmap/colmap/issues/2096 I found a code regression introduced with commit https://github.com/colmap/colmap/commit/67029ad21205fac3d149e06000c1e20bf4be1b80
This affects model_cropper and model_splitter tools.
As the previous implementation used the Image::ResetPoint3DForPoint2D method inside the loop, the num_points3D member was reset to 0 correctly.
https://github.com/colmap/colmap/blob/1f95f3ee74fdbc020ef2dca190ec56958ea5f9e1/src/colmap/scene/image.cc#L97-L103
When directly assigning the kInvalidPoint3DId value, new_image keeps the value of the source num_points3D representing an incorrect state of the newly created cropped_reconstruction and …
=> Fix model_cropper not resetting image.num_points3D of cropped_rec

src/colmap/feature/sift.cc
This information is helpful in understanding what is being used at runtime. We lost this info with recent changes to logging.
=> Log info about created feature extractor/matcher types

src/colmap/geometry/rigid3.h, src/colmap/geometry/rigid3_test.cc, src/pycolmap/geometry/bindings.cc
Reference: 
- https://gtsam.org/2021/02/23/uncertainties-part3.html
- https://github.com/microsoft/lamar-benchmark/blob/fa6f5409364a11d5e59a57cec2ad1d7f9e6a8888/scantools/capture/pose.py#L99
The adjoint matrix is very useful on propagating uncertainty for Rigid3d. 
A unit test is added as well.
=> Support Adjoint matrix computation for Rigid3d

src/colmap/estimators/cost_functions.h
Just found a long-standing bug from https://github.com/colmap/colmap/pull/2378 in both cost functions in pose graph optimization:
After LLT it should be ``L_matrix.transpose()`` rather than ``L_matrix`` that is left multiplied on the residuals.
Moreover, SVD is faster and more stable compared to ``covariance.inverse().llt()``. I have updated this as well.
=> Fix cost functions for pose graph optimization

src/colmap/estimators/cost_functions.h
[Minor] Align with the S_{-1/2}f(x) in the ceres doc here http://ceres-solver.org/nnls_covariance.html. Move ``.transpose()`` into the SqrtInformation matrix.
=> Align with the convention of ceres doc on SqrtInformation.

src/colmap/estimators/fundamental_matrix.cc, src/colmap/estimators/fundamental_matrix_test.cc
Minimal 8-point case is ~5 faster. Unchanged performance on over-constrained case. Added some more test coverage.
=> Faster 8-point fundamental matrix estimator

src/colmap/estimators/covariance.cc, src/colmap/estimators/covariance.h, src/pycolmap/estimators/covariance.cc
This PR includes faster covariance computation for small blocks, as a follow up for https://github.com/colmap/colmap/pull/2610. This is achieved by storing the inversion of the triangular matrix L from sparse Cholesky rather than storing the full covariance matrix. 
This brings ~5x constant speed up on the computation of per-image pose covariance while the asymptotic complexity is still cubic (as in the table below, the sparse cholesky operation is already cubic).
Below are some benchmark timing results for per-pose covariance estimation. Control points were used to fix the Gauge ambiguity.
| # images   | # pose parameters | sparse cholesky (in both methods)  | full time before from https://github.com/colmap/colmap/pull/2610 | full time in this PR | 
| -------- | -------- | -------- | …
=> Faster covariance computation for small blocks

scripts/python/database.py
AttributeError: `np.NaN` was removed in the NumPy 2.0 release - we should use `np.nan` instead. Originally reported in https://github.com/cvg/Hierarchical-Localization/pull/405
=> Numpy 2 compatibility

cmake/colmap-config.cmake.in
Seems like this line went missing in https://github.com/colmap/colmap/commit/4afd5d986823fea0b629b958fc2bb3e25695c99f
=> Reset CMAKE_MODULE_PATH to previous value

src/colmap/sfm/observation_manager.cc
This potential bug was discovered when I tried to use `colmap point_triangulator` command to perform 3d reconstruction with known camera poses, following [this guide](https://colmap.github.io/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses)
I think the issue is the following: 
* user-provided images.txt with known poses can include all images in a dataset.
* However for database cache creation (database_cache.cc line 145), some of the images may be skipped due to lack of connections.
* The combination of the above two _may_ create a discrepancy in this usecase.
The error message I had is:
```
==============================================================================
Loading model
==============================================================================
I0812 …
```
=> Observation manager needs to check if image_id exists before query operations

src/colmap/feature/pairing.cc
This bug dates back to commit [
Improve code of feature matchers](https://github.com/colmap/colmap/commit/d2b130bb79c1648d5252acb3081242c74c2c21b2)
According to this doc in `colmap/src/colmap/controllers/feature_matching.h`:
```c++
// Sequentially match images within neighborhood:
//
// +-------------------------------+-----------------------> images[i]
//                      ^          |           ^
//                      |   Current image[i]   |
//                      |          |           |
//                      +----------+-----------+
//                                 |
//                        Match image_i against
//
//                    image_[i - o, i + o]        with o = [1 .. overlap]
//                    image_[i - 2^o, i + 2^o]    (for quadratic overlap)
//
// …
```
=> Fix: sequential matcher overlap number should be inclusive

src/colmap/exe/feature.h
Noticed a table in exe/feature.h was mangled. Happened when clang-format options where simplified in https://github.com/colmap/colmap/pull/1950.
This reverts it to what it used to look like: https://github.com/colmap/colmap/blob/3947f67243e4924683e14481b4dbb44593950c52/src/colmap/exe/feature.h#L44-L52 and turns off clang-format for those lines.
=> Fix table mangled by clang-format

src/colmap/controllers/option_manager.cc, src/colmap/estimators/bundle_adjustment.h
Addresses https://github.com/colmap/colmap/issues/2703
* Make sure we write out parameters in full precision, so small values do not get truncated to 0.
* Conservatively relax the bundle adjustment convergence thresholds. Before this PR, bundle adjustment would always run for the full iterations because of 0 tolerances.
=> Write out options to ini in full precision, relax bundle adjuster convergence

src/colmap/controllers/automatic_reconstruction.cc, src/colmap/controllers/automatic_reconstruction.h, src/colmap/controllers/incremental_mapper.cc, src/colmap/controllers/incremental_mapper.h, src/colmap/controllers/option_manager.cc, src/colmap/estimators/CMakeLists.txt, src/colmap/estimators/bundle_adjustment.cc, src/colmap/estimators/bundle_adjustment.h, src/colmap/estimators/manifold.h, src/colmap/util/cuda.cc
This PR implements enhancement: https://github.com/colmap/colmap/issues/2643. It builds upon Ceres' recent CUDA_SPARSE solver type.
Initial experiments show significant runtime improvements. On my machine with an Intel Core i9 10920X and an NVidia RTX 2070, I see a consistent 3x speedup for reconstructions with ~500-5000 images. For smaller problems with ~100 images, the runtime is roughly equivalent. These experiments were done using CUDA 12.5 and cudss 0.3.0.
For now, the feature is disabled by default and requires explicit enabling of the option. This is because no robustness is implemented against situations where the GPU does not have enough memory and some of the thresholds that determine the usage of sparse direct vs. indirect solvers need to be tuned in this new scenario.
=> Add support for CUDA sparse BA solver

src/colmap/retrieval/visual_index.h
`VisualIndex::Quantize` is called from only `VisualIndex::Build` and modifies the member variable `visual_words_`. 
In the current implementation, we cannot easily guess what `Quantize` actually modifies when reading the `Build` function. 
I made the `VisualIndex::Quantize` const and made it explicitly return the output.
=> Make VisualIndex::Quantize const to improve readability

src/colmap/estimators/bundle_adjustment.cc
I think that the macro CUDA_ENABLED should be COLMAP_CUDA_ENABLED instead, in the new bundle adjustment code that directs Ceres to use the GPU.
=> Fix CUDA_ENABLED macro in new bundle adjustment code

src/colmap/controllers/incremental_mapper.cc, src/colmap/controllers/incremental_mapper.h, src/colmap/controllers/option_manager.cc, src/colmap/estimators/bundle_adjustment.cc, src/colmap/estimators/bundle_adjustment.h, src/pycolmap/estimators/bundle_adjustment.cc, src/pycolmap/sfm/incremental_mapper.cc
* Adds support for using Ceres' CUDA based dense solver for BA.
* Adds some initial heuristic thresholds to switch between CPU and GPU based solvers.
* GPU-based solvers are still disabled by default and require explicit enabling through e.g. `--Mapper.ba_use_gpu` or `--BundleAdjustment.use_gpu`.
* The heuristic thresholds would benefit from a more sophisticated tuning based on CPU/GPU capability. Not sure if feasible.
=> Add CUDA-based dense BA solver

src/colmap/controllers/feature_matching_utils.cc, src/colmap/controllers/feature_matching_utils.h, src/colmap/feature/CMakeLists.txt, src/colmap/feature/index.cc, src/colmap/feature/index.h, src/colmap/feature/index_test.cc, src/colmap/feature/matcher.cc, src/colmap/feature/matcher.h, src/colmap/feature/sift.cc, src/colmap/feature/sift.h, src/colmap/feature/sift_test.cc, src/colmap/mvs/workspace.cc, src/colmap/mvs/workspace.h, src/colmap/util/cache.h, src/colmap/util/cache_test.cc, src/colmap/util/types.h
* Simplifies the caching logic for both CPU and GPU based matching.
* Introduces a new thread-safe LRU cache that allows to efficiently cache the FLANN-based descriptor index for CPU-based matching. As a result, CPU-based matching speed improves by ~20-30%.
* Extracts the FLANN-based descriptor index as a separate interface and adds test coverage.
* Fixes a race-condition in the dense reconstruction workspace cache.
=> Improved and simplified caching in feature matching

src/colmap/util/logging.h
To be able to use the macro when COLMAP is used as a third party
=> Fix colmap namespace in the macro support of logging.

src/colmap/util/base_controller.cc, src/colmap/util/base_controller.h, src/colmap/util/threading.cc, src/colmap/util/threading.h, src/pycolmap/pipeline/sfm.cc
Callable objects can be expensive to copy. This enables the callsite to add callbacks by move. No change of behavior for existing callsites.
=> Add callbacks by move

src/colmap/controllers/feature_matching.cc, src/colmap/controllers/feature_matching.h, src/colmap/feature/matcher.cc, src/colmap/feature/matcher.h, src/colmap/feature/pairing.cc, src/colmap/feature/pairing.h, src/colmap/feature/pairing_test.cc
Consistently implements transitive matching through pair generation interface. This allows to implement tests against the pair generation. No change in behavior.
=> Implement transitive matcher with pair generator + tests

src/colmap/estimators/pose.h, src/colmap/estimators/triangulation.h, src/colmap/sfm/incremental_mapper.cc, src/colmap/sfm/incremental_triangulator.cc, src/pycolmap/estimators/absolute_pose.cc, src/pycolmap/estimators/generalized_absolute_pose.cc, src/pycolmap/estimators/triangulation.cc
https://github.com/colmap/colmap/pull/2721 inadvertently broke the default options for `pycolmap.estimate_triangulation`, which I then realized were completely wrong. To fix this, I think that `EstimateTriangulationOptions` and `AbsolutePose{Estimation,Refinement}Options` should provide sensible defaults instead of, as we have been doing it so far, monkey-patching some values in Python. This PR doesn't change the default behavior of COLMAP and only slightly affects PyCOLMAP's `estimate_triangulation`/`absolute_pose_estimation`/`rig_absolute_pose_estimation` to be consistent with the corresponding COLMAP options.
=> Provide reasonable defaults for some estimator options

src/colmap/mvs/meshing.cc, src/pycolmap/pipeline/meshing.cc
Fix a long-standing bug affecting the Python bindings of Delaunay meshing. Caught when checking stubs locally with CGAL enabled - not caught in the CI because CGAL is disabled there.
=> Fix mismatched Delaunay meshing options

src/colmap/sfm/incremental_mapper.cc
Fixes https://github.com/colmap/colmap/issues/2582. Should make no difference in the default `IncrementalPipeline` because `IterativeGlobalRefinement` comes right after `IterativeLocalRefinement` but it could save some compute in a custom pipeline.
=> Add missing ClearModifiedPoints3D

src/colmap/sfm/incremental_triangulator.cc
The order in which the points are completed does not matter, so the change of FIFO to LIFO queue produces the same results.
=> Avoid unnecessary copy of queue in IncrementalTriangulator::Complete()

src/colmap/util/logging.h
Uses __builtin_expect() under the hood. Other THROW_CHECK macros already have it because they use the glog macros under the hood.
=> Branch prediction for THROW_CHECK_NOTNULL

src/colmap/scene/image.h
To switch camera before one needs to first reset camera id and camera pointer and then set both again. This enables direct switching which can be more flexible in both C++ and Python.
=> Support switching camera directly with camera pointer

src/colmap/controllers/incremental_mapper.cc, src/colmap/util/CMakeLists.txt, src/colmap/util/endian.cc, src/colmap/util/endian.h
This PR fixes two issues:
1. Adds missing boost includes to define the endian macros. Moves the implementation to the .cc file so we don't transitively propagate the boost includes.
2. The boost endian macros have been renamed from `BOOST_*_ENDIAN` to `BOOST_ENDIAN_*_BYTE`.
=> Fix little/big endian detection

src/colmap/estimators/bundle_adjustment.cc
This PR attempts to fix #2746 .
cudss is available in ceres since 2.3.0.
In [ceres 2.2.0](https://github.com/ceres-solver/ceres-solver/releases/tag/2.2.0), CUDA_SPARSE is used for the CGNR solver instead of the SPARSE_SCHUR solver.
=> Fix options for CUDA sparse BA solver

src/colmap/optim/loransac.h, src/colmap/optim/ransac.h, src/colmap/optim/support_measurement.cc, src/colmap/optim/support_measurement.h, src/colmap/optim/support_measurement_test.cc
=> Rename SupperMeasurer::Compare for improved readability

src/pycolmap/scene/reconstruction.cc
I'm working on a SLAM system, and writing the results in colmap format using pycolmap. Computing reprojection error is trivial, but it would be nice of pycolmap can do it as well.
=> Expose UpdatePoint3DErrors to pycolmap

.github/workflows/build-ubuntu.yml, doc/conf.py, pycolmap/generate_stubs.sh, pycolmap/pyproject.toml, ruff.toml, scripts/format/python.sh, scripts/python/database.py, scripts/python/plyfile.py
=> Switch to the Ruff Python formatter

src/colmap/estimators/bundle_adjustment.cc, src/colmap/estimators/cost_functions.h, src/colmap/estimators/cost_functions_test.cc, src/colmap/estimators/generalized_pose.cc, src/colmap/estimators/pose.cc, src/pycolmap/estimators/cost_functions.cc
As in the title, rename all the cost functions to cost functors, as in here: https://github.com/ceres-solver/ceres-solver/blob/master/include/ceres/autodiff_cost_function.h#L161. 
Preparatory for the covariance update.
=> Customized cost functions should be functors instead

.github/workflows/build-ubuntu.yml, pycolmap/pyproject.toml, scripts/format/c++.sh, src/colmap/estimators/bundle_adjustment_test.cc, src/colmap/util/logging_test.cc, src/pycolmap/pybind11_extension.h
Installing it from pypi makes it easier to rely on a consistent clang-format version on different platforms. It also allows us to use a more recent version.
=> Install and use newer clang-format from pypi

src/pycolmap/scene/reconstruction.cc
Currently, they return a copy - this a bug and not intended.
=> Return a reference in Reconstruction.image/camera/point3D

src/colmap/scene/reconstruction.h
- Calling `reconstruction.Image(image_id)` for a nonexistent image ID raises an exception with the uninformative message `_Map_base::at`. This is especially confusing for Python users. This PR makes the exception message more informative.
- This PR also shares the implementations of the const and non-const getters, as suggested here: https://stackoverflow.com/a/856839 Does it still make sense to keep these implementations inlined?
=> More informative exception if invalid access of image/camera/point3D

src/thirdparty/CMakeLists.txt
Otherwise, the binaries are not redistributable across different machines. If users want to squeeze out more performance on a specific machine, they can add the flags easily during CMake configuration time.
=> Disable -march=native flags in poselib

src/thirdparty/CMakeLists.txt
The change https://github.com/colmap/colmap/commit/461cd981d10c1ca2c96b6a152342a5b565654f03 results in the following warning in the configure step of CMake 3.27.4:
```
CMake Warning (dev) at build/_deps/poselib-src/CMakeLists.txt:24 (option):
Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
--help-policy CMP0077" for policy details.  Use the cmake_policy command to
set the policy and suppress this warning.
For compatibility with older versions of CMake, option is clearing the
normal variable 'MARCH_NATIVE'.
This warning is for project developers.  Use -Wno-dev to suppress it.
```
This PR suppresses the warning.
=> Remove warning in configure step

cmake/FindDependencies.cmake
Supersedes https://github.com/colmap/colmap/pull/2848
=> Suppress CMP0167 warning for FindBoost under CMake 3.30 or newer

src/colmap/estimators/bundle_adjustment.cc
Small fix for the (very unlikely?) case where CUDA sparse solvers are available but the dense solvers are not.
=> Select CUDA device when bundle adjustment uses GPU

src/colmap/scene/reconstruction.cc, src/colmap/scene/reconstruction.h, src/colmap/scene/reconstruction_test.cc, src/pycolmap/scene/reconstruction.cc
Previous copying behavior is very dangerous after the introduction of camera pointer.
=> Fix copying behaviors of Reconstruction regarding camera pointers

src/pycolmap/helpers.h
https://github.com/colmap/colmap/pull/2842 removed the custom `__repr__` for some objects like `Image`. Pycolmap then falls back to enumerating all the attributes, which is suboptimal - for example for `Image` we don't want to print all 2D points to void bloating the console output. This PR recovers the previous behavior for objects for which `stringstream << obj` is defined.
=> Use the C++ string representation for Python dataclass objects

src/colmap/sensor/models.h
Attempt on https://github.com/colmap/colmap/issues/2802 (improvement but did not manage to fully fix as discussed in the post below)
Remove templating of CamFromImg as it is never used in the optimization (and is tricky to be used in the optimization due to the unrolling in IterativeUndistortion). 
Use Jet from ceres to enable analytical Jacobian in the IterativeUndistortion.
=> Use analytical Jacobian in IterativeUndistortion. Add trust region

src/colmap/estimators/covariance.cc
This is a very crucial fix. (LD) can be very ill-conditioned on the diagonal, which results in nan at matrix inversion. So we should do inversion only on the L matrix.
=> Improve the conditioning of covariance estimation

src/colmap/controllers/feature_matching.cc, src/colmap/feature/matcher.cc, src/colmap/feature/matcher.h, src/colmap/feature/pairing.cc
It turns out one cannot concurrent read from the database and begin a transaction. This could happen in rare cases during vocabulary tree based matching, as the querying of the vocabulary tree is performed concurrently to the main matching controller thread. In this case, one thread might simultaneously read and begin a transaction. This causes a deadlock if unlucky. With this PR, this cannot happen anymore.
=> Fix rare deadlock during matching due to concurrent database access

src/colmap/controllers/automatic_reconstruction.cc, src/colmap/controllers/automatic_reconstruction.h, src/colmap/exe/sfm.cc
* Adds missing single_camera_per_folder option.
* Allows optional feature extraction/matching.
=> Add new and missing options to automatic reconstructor

src/colmap/exe/model.cc
This allows to conveniently align one model to another one, if they have the common registered images. This could be done before but required some custom scripting.
=> Enable model alignment to reference model

src/colmap/scene/reconstruction.h
Fixes the following warnings triggered on almost every file because of transitive includes:
```
colmap/scene/reconstruction.h(279): warning C4101: 'e': unreferenced local variable
```
=> Fix unused variable warnings under MSVC

pycolmap/README.md
The path for the example in the pycolmap subfolder has changed. This MR incorporates this change into the corresponding README.
=> [doc] Fix path to example in README.md

doc/tutorial.rst
The menu item ‘Feature Matching’ has changed in the GUI. This PR incorporates this change into the tutorial.
=> [doc] Fix typo for gui menu item

src/colmap/scene/image.h, src/colmap/ui/model_viewer_widget.cc, src/pycolmap/scene/image.cc
Since we changed the behavior to throw an exception on missing image pose, this can cause a crash in the viewer. This case is now handled more gracefully.
=> Gracefully handle missing image pose in viewer

pycolmap/examples/custom_bundle_adjustment.py, pycolmap/examples/custom_incremental_mapping.py, scripts/format/python.sh, src/colmap/controllers/bundle_adjustment.cc, src/colmap/estimators/alignment.cc, src/colmap/estimators/alignment.h, src/colmap/estimators/bundle_adjustment.cc, src/colmap/estimators/bundle_adjustment.h, src/colmap/estimators/bundle_adjustment_test.cc, src/colmap/estimators/covariance_test.cc, src/colmap/exe/sfm.cc, src/colmap/sfm/incremental_mapper.cc, src/pycolmap/estimators/bundle_adjustment.cc
* Defines a single consistent abstract interface for bundle adjustment.
* Reuses functionality between different bundle adjusters using composition rather than inheritance.
* Extracts the pose prior alignment to the alignment module. Ideally needs tests but this remains a TODO.
* The problem setup is now performed when the bundle adjuster is created and, as such, disentangled from the solving of the problem. This renders the current awkward SetUpProblem unnecessary.
* The idea later is then to pass a bundle adjuster object to a simplified covariance estimation interface.
=> Modernized bundle adjustment interface

src/colmap/estimators/alignment.cc, src/colmap/estimators/bundle_adjustment.cc, src/colmap/estimators/similarity_transform.h, src/colmap/estimators/similarity_transform_test.cc, src/colmap/optim/loransac_test.cc, src/pycolmap/estimators/bindings.cc, src/pycolmap/estimators/similarity_transform.cc
Test:
```python
import pycolmap
import numpy as np
tgt_from_src = pycolmap.Sim3d(3, np.random.RandomState(0).randn(3), np.arange(3)+1)
n_points = 50
p_src = np.random.RandomState(1).randn(n_points, 3)
p_tgt = tgt_from_src * p_src
tgt_from_src_est = pycolmap.estimate_sim3d(p_src, p_tgt)
print('least-squares:')
print(tgt_from_src)
print(tgt_from_src_est)
inlier_ratio = 0.5
n_inliers = int(inlier_ratio * n_points)
n_outliers = n_points - n_inliers
for i in np.random.RandomState(2).choice(n_points, n_outliers, replace=False):
p_src[i] = np.random.RandomState(i).randn() * 10
max_error = 0.1
ret = pycolmap.estimate_sim3d_robust(p_src, p_tgt, {"max_error": max_error})
n_inliers_real = np.count_nonzero(np.linalg.norm(p_tgt - tgt_from_src * p_src, axis=1) < max_error)
print('robust:') …
```
=> Bind the estimation of Sim3d

.github/workflows/build-windows.yml, cmake/CMakeHelper.cmake, src/colmap/controllers/incremental_pipeline_test.cc, src/colmap/feature/pairing.cc, src/colmap/feature/pairing_test.cc, src/colmap/scene/database_cache.cc, src/colmap/scene/reconstruction_io.cc, src/colmap/util/CMakeLists.txt, src/colmap/util/gtest_main.cc
Without the custom main function introduced in this PR, we get warnings about glog not being initialized, since the default gtest/gmock main functions do not initialize glog.
=> Initialize glog in custom gmock main function

src/pycolmap/estimators/absolute_pose.cc, src/pycolmap/estimators/alignment.cc, src/pycolmap/estimators/essential_matrix.cc, src/pycolmap/estimators/fundamental_matrix.cc, src/pycolmap/estimators/generalized_absolute_pose.cc, src/pycolmap/estimators/homography_matrix.cc, src/pycolmap/estimators/similarity_transform.cc, src/pycolmap/estimators/triangulation.cc, src/pycolmap/estimators/two_view_geometry.cc, src/pycolmap/helpers.h
With a best effort of raising deprecation warnings for  renamed function names. For example:
```
>>> pycolmap.essential_matrix_estimation()
<stdin>:1: DeprecationWarning: essential_matrix_estimation() is deprecated, use estimate_essential_matrix() instead.
...
```
Other modules follow in separate PRs.
=> Consistent interface and various improvements for pycolmap/estimators

src/colmap/image/line.h, src/colmap/image/line_test.cc
We could alternatively exclude colmap/image/line altogether.
=> Exclude DetectLineSegments if LSD is disabled

src/colmap/sensor/bitmap.cc, src/colmap/sensor/bitmap_test.cc
Hello ! I had some issues reading 16bit per channel pngs with the feature extractor. I tracked the issue to [this line](https://github.com/colmap/colmap/blob/ec2180683006fced762994b42fda6df03e140ff7/src/colmap/sensor/bitmap.cc#L582) returning a null pointer. 
Turns out FreeImage cant transform these images directly into grayscale as described [here](https://sourceforge.net/p/freeimage/discussion/36110/thread/a886679e68/). This happens at line 104 in the FreeImage Conversion8.cpp file:
```C++
FIBITMAP * DLL_CALLCONV
FreeImage_ConvertTo8Bits(FIBITMAP *dib) {  // Called by FreeImage_ConvertToGreyscale
if (!FreeImage_HasPixels(dib)) {
return NULL;
}
const FREE_IMAGE_TYPE image_type = FreeImage_GetImageType(dib);
if (image_type != FIT_BITMAP && image_type != FIT_UINT16) {   // <----- Here …
```
=> Enable reading 16bit/channel (png) images to grayscale

src/pycolmap/feature/sift.cc, src/pycolmap/geometry/bindings.cc, src/pycolmap/geometry/essential_matrix.cc, src/pycolmap/geometry/homography_matrix.cc, src/pycolmap/pipeline/match_features.cc
For Sift, I want to move to a consistent set of options, where we use the C++ ones as the default. We'll issue a deprecation warning:
```
>>> import pycolmap
>>> pycolmap.Sift(pycolmap.SiftExtractionOptions())
I20241120 09:56:59.974107 202499 sift.cc:727] Creating SIFT CPU feature extractor
<pycolmap._core.Sift object at 0x106511230>
>>> pycolmap.Sift()
<stdin>:1: DeprecationWarning: No SIFT extraction options specified. Setting them to peak_threshold=0.01, first_octave=0, max_image_size=7000 for backwards compatibility. If you want to keep the settings, explicitly pass them, because the defaults will change in the next major release.
I20241120 09:57:04.519587 202499 sift.cc:727] Creating SIFT CPU feature extractor
<pycolmap._core.Sift object at 0x106325630>
```
=> Cleanup of remaining pycolmap interfaces

src/pycolmap/estimators/fundamental_matrix.cc, src/pycolmap/helpers.h
- https://github.com/colmap/colmap/pull/2923 missed to rename `fundamental_matrix_estimation` to `estimate_fundamental_matrix`
- Display the deprecation in the doc
=> Improvements to deprecated pycolmap members

doc/conf.py
Fixes https://github.com/colmap/colmap/issues/2892:
I will improve the rendering of overloads in a subsequent PR.
=> Make sphinx show the pycolmap constructors

src/colmap/geometry/essential_matrix_test.cc, src/colmap/geometry/gps_test.cc, src/colmap/geometry/pose_test.cc, src/colmap/image/undistortion_test.cc, src/colmap/math/polynomial_test.cc, src/colmap/optim/least_absolute_deviations_test.cc, src/colmap/retrieval/geometry_test.cc, src/colmap/scene/two_view_geometry_test.cc, src/colmap/util/CMakeLists.txt, src/colmap/util/eigen_matchers.h, src/colmap/util/eigen_matchers_test.cc
Using gmock matchers instead of `a.isApprox(b)` has the advantage of providing more readable output to the user. In case of a test failure, the matrix shape or contents will be printed to the console. Another benefit is that one can embed them into more complex gmock match expressions. This paves the way for better testing some of our interfaces through mocks and fakes.
=> Introduce gmock Eigen matrix matchers

src/pycolmap/logging.h
Fixes https://github.com/colmap/colmap/issues/2895. We run a similar check in pyceres: https://github.com/cvg/pyceres/pull/59
=> Prevent double initialization of glog for <=0.5

src/colmap/ui/log_widget.cc
Fixes the following warning when Courier is not available on the system. Will use any available monospace/fixed font.
```
qt.qpa.fonts: Populating font family aliases took 122 ms. Replace uses of missing font family "Courier" with one that exists to avoid this cost.
```
=> Cross platform usage of monospace font

src/colmap/estimators/generalized_relative_pose.cc, src/colmap/estimators/generalized_relative_pose.h, src/colmap/estimators/generalized_relative_pose_test.cc
The poselib solver is much more stable and also only needs 6 vs. 8 points in the minimal case to work well in practice.
=> Use poselib's minimal solver for generalized relative pose

src/colmap/estimators/absolute_pose.cc
Recent profiling showed that reusing the allocations does not help with performance.
=> Remove unnecessary thread_local storage attribute in PNP estimators

src/colmap/feature/pairing.cc
The behavior does not change but this makes the choice more explicit and documents the reasoning.
=> Explicitly set number of visual word neighbors and document reasoning

pycolmap/examples/custom_bundle_adjustment.py, src/pycolmap/estimators/bindings.cc, src/pycolmap/estimators/ceres_bindings.cc
Relevant discussion here: https://github.com/colmap/colmap/issues/2978
No need for ``import ceres`` in ``custom_bundle_adjustment.py`` anymore (relevant discussion: https://github.com/colmap/colmap/pull/2896)
=> Add back some ceres bindings to use pycolmap bundle adjustment without pyceres

vcpkg.json
Unfortunately, vcpkg defaults to not producing schur specializations for ceres. Without them, bundle adjustment is much slower (at the cost of longer compile times and larger binary size).
=> Enable ceres schur specializations in vcpkg build

.github/workflows/build-mac.yml, .github/workflows/build-pycolmap.yml, .github/workflows/build-ubuntu.yml, .github/workflows/build-windows.yml
Cancels a previous currently running build upon push to PR/branch/tag. This should help with avoiding throttling by Github actions when many people work in parallel in different PRs and push changes frequently.
=> Cancel previous Github action runs upon push

pycolmap/pyproject.toml
Installation current fails with the following error:
```
Download CCache
Installation failed with an error
A parameter cannot be found that matches parameter name 'MaximumRetryCount'.
```
Likely due to powershell vs. powershell core feature differences. This PR switches to powershell core.
=> Fix ccache installation in pycolmap windows CI

.github/workflows/build-pycolmap.yml, .github/workflows/build-windows.yml
The Github actions cache only supporting 10GB makes our builds unusably slow. This PR attempts to configure the cache against an Azure blob storage container that I'll pay out of my pocket.
=> Use Azure blob storage as vcpkg binary cache

cmake/FindDependencies.cmake, src/colmap/retrieval/CMakeLists.txt
Fixes: https://github.com/colmap/colmap/issues/2977
=> Add missing openmp flags in retrieval for flann parallelization

.github/workflows/build-pycolmap.yml, .github/workflows/build-windows.yml
Currently, PR from forks cannot run our CI pipeline, because secrets are not accessible for PRs originating from forks. See e.g. https://github.com/colmap/colmap/pull/3024. This PR fixes the issue by letting PRs from forks read but not write to the cache.
=> Separate read and write SAS tokens for vcpkg binary cache

.github/workflows/build-pycolmap.yml, .github/workflows/build-windows.yml
The Github documentation on this topic is very fuzzy. Unfortunately, it turns out that even action env variables are not readable by forks. See: https://github.com/orgs/community/discussions/44322. The only option is to define the variable directly in the action definition.
=> Define vcpkg binary cache source inline

src/colmap/mvs/consistency_graph.cc, src/colmap/mvs/mat.cc, src/colmap/util/endian.h, src/colmap/util/endian_test.cc, src/colmap/util/file.cc, src/colmap/util/file.h, src/colmap/util/file_test.cc
Several changes in this PR:
* Improved interface for WriteBinaryBlob now takes spans to allow for more generic inputs.
* Little/big endian doesn't really make sense for generic binary data. The data should already be in consistent format before being converted into raw bytes.
* Added missing unit tests.
=> Improve interface for ReadWriteBinaryBlob and add tests

doc/faq.rst, doc/tutorial.rst, src/colmap/controllers/automatic_reconstruction.h, src/colmap/exe/vocab_tree.cc, src/colmap/feature/pairing.h, src/colmap/retrieval/CMakeLists.txt, src/colmap/retrieval/resources.h, src/colmap/retrieval/visual_index.h, src/colmap/retrieval/visual_index_test.cc, src/colmap/util/file.cc, src/colmap/util/file.h, src/colmap/util/file_test.cc
This PR adds automatic download and caching functionality for vocabulary trees. Sample output:
```
$ colmap vocab_tree_matcher --database_path ~/data/south-building/database.db
I20241212 18:17:51.708911 427449 misc.cc:44] 
==============================================================================
Feature matching
==============================================================================
I20241212 18:17:51.724920 427450 sift.cc:1426] Creating SIFT GPU feature matcher
I20241212 18:17:51.755941 427449 pairing.cc:234] Generating image pairs with vocabulary tree...
I20241212 18:17:51.756253 427449 file.cc:356] Downloading file from: https://github.com/colmap/colmap/releases/download/3.11.1/vocab_tree_flickr100K_words256K.bin
I20241212 18:17:56.891381 427449 file.cc:361] Caching file …
```
=> Automatically download and cache vocabulary tree

src/colmap/sfm/incremental_mapper.cc, src/colmap/sfm/incremental_mapper_impl.cc, src/colmap/sfm/incremental_mapper_impl.h, src/colmap/sfm/observation_manager.cc, src/colmap/sfm/observation_manager.h
As mentioned in https://github.com/colmap/colmap/pull/3042, there are some dependencies in the graph that we need to take care of to avoid inconsistency, notably:
* ``ObservationManager`` and ``DatabaseCache`` shares a same ``CorrespondenceGraph`` object, so should not be listed as input together to a static method
* ``ObservationManager`` has a reference to the ``Reconstruction`` object, so should not be listed as input together with a ``Reconstruction`` object to a static method
This PR contains the updates as follows:
* use const ref rather than smart pointers as input in the algorithm class
* use ``NumCorrespondencesForImage`` from ``CorrespondenceGraph`` rather than ``ObservationManager`` to avoid dependent input
* add getter for the ``Reconstruction`` object to the …
=> Avoid dependent inputs in IncrementalMapperImpl

src/colmap/estimators/coordinate_frame_test.cc, src/colmap/exe/model.cc, src/colmap/geometry/CMakeLists.txt, src/colmap/geometry/normalization.cc, src/colmap/geometry/normalization.h, src/colmap/geometry/normalization_test.cc, src/colmap/scene/reconstruction.cc, src/colmap/scene/reconstruction.h, src/colmap/scene/reconstruction_test.cc, src/pycolmap/geometry/bindings.cc, src/pycolmap/scene/reconstruction.cc
* Use nth_element instead of sort for faster ordering.
* Normalize in double precision to better handle large coordinates (e.g., GPS).
* Use Eigen's AlignedBox instead of pair of Vector3d for bbox.
* Extract bbox and centroid computation into reusable geometry module function. Add some more tests.
=> Improvements for reconstruction normalization / bbox / centroid

src/colmap/estimators/CMakeLists.txt, src/colmap/estimators/affine_transform.cc, src/colmap/estimators/affine_transform.h, src/colmap/estimators/affine_transform_test.cc, src/colmap/estimators/similarity_transform.cc, src/colmap/estimators/similarity_transform.h, src/colmap/estimators/similarity_transform_test.cc, src/colmap/geometry/essential_matrix.cc, src/colmap/geometry/normalization.cc, src/colmap/geometry/rigid3.h, src/colmap/geometry/rigid3_test.cc, src/colmap/retrieval/vote_and_verify.cc, src/colmap/util/types.h, src/pycolmap/estimators/affine_transform.cc, src/pycolmap/estimators/similarity_transform.cc, src/pycolmap/geometry/bindings.cc
* Add new functions EstimateRigid3d, EstimateRigid3dRobust, EstimateAffine2d, Estimate2dRobust (consistent with existing EstimateSim3d and Sim3dRobust).
* Improved tests for all of the transformations.
* Expose estimate_rigid3d and estimate_rigid3d_robust in pycolmap bindings.
* Add Rigid3d::FromMatrix (consistent with Sim3d::FromMatrix).
=> Consistent interface/tests for rigid3d/sim3d/affine2d, pycolmap bindings for rigid3d

src/pycolmap/estimators/ceres_bindings.cc
For similar purpose as https://github.com/cvg/pyceres/pull/62, just in the other direction.
=> Add copy constructor support for solver-related ceres bindings

src/colmap/controllers/option_manager.cc
Selecting only the top-level features in the vocab tree has significant impact on the speed of the indexing/querying with a trade-off in terms of quality. The chosen thresholds are empirically chosen. In my experience, even when using only 256 features, the precision/recall metrics are still quite good.
=> Set max_num_features automatically per quality level

src/colmap/controllers/automatic_reconstruction.cc, src/colmap/exe/sfm.cc
Only creates OpenGL context if feature extraction and matching stages are executed on the GPU. Previously, we would always create a context, even if not necessary.
=> Only create OpenGL context in automatic reconstruction if necessary

src/pycolmap/estimators/covariance.cc
Fixes compiler warning `warning: braces around scalar initializer`.
=> Remove unnecessary braces around initializer in pycolmap/covariance

docker/Dockerfile
Fixes https://github.com/colmap/colmap/issues/3118
=> Install missing libcurl4 runtime library in dockerfile

src/colmap/scene/synthetic.cc
Passing zero standard deviation to the Gaussian distribution causes undefined behavior in some standard library implementations.
=> Fix synthetic prior generation when stddev=0

benchmark/runtime/cost_functions.cc
Missed from https://github.com/colmap/colmap/pull/2880. This benchmarking folder is not covered by the CI pipeline.
=> Fix cost functor convention for benchmarking

src/colmap/scene/frame.h, src/colmap/scene/frame_test.cc, src/colmap/scene/image.h, src/colmap/sensor/rig_calib.cc, src/colmap/sensor/rig_calib.h, src/colmap/sensor/rig_calib_test.cc
Let's save us some characters to write going forward. Was starting to play around with serialization and got already annoyed by typing out the full RigRalibration name.
=> Rename RigCalibration to RigCalib

src/colmap/geometry/pose.cc, src/colmap/geometry/pose.h, src/colmap/geometry/pose_test.cc, src/colmap/geometry/rigid3.cc, src/colmap/geometry/rigid3.h, src/colmap/geometry/rigid3_test.cc, src/pycolmap/geometry/bindings.cc
The covariance propagation of pose inverse via adjoint introduced in https://github.com/colmap/colmap/pull/2598 followed the lamar convention, which was just found to be actually broken here: https://github.com/microsoft/lamar-benchmark/pull/84.
This PR fixes the propagation and added more cycle-consistent tests on the property of the adjoint matrix. To simplify the code for calculating adjoint inverse the function ``CrossProductMatrix`` is moved into ``rigid3.h``.
=> Fix covariance propagation of pose inverse

src/colmap/estimators/essential_matrix.cc, src/colmap/estimators/essential_matrix.h, src/colmap/estimators/essential_matrix_test.cc, src/colmap/estimators/pose.cc, src/colmap/estimators/two_view_geometry.cc, src/colmap/estimators/utils.cc, src/colmap/estimators/utils.h, src/pycolmap/estimators/essential_matrix.cc
This is the first in a series of PRs to support cameras with >180deg FOV (including spherical cameras). This PR should result in no behavioral change other than changes up to numerical precision.
=> [Spherical Camera Support] Change essential matrix estimation to use camera rays

src/colmap/geometry/rigid3.h
This was a big confusion. I added some comments to explain why the fix in https://github.com/colmap/colmap/pull/3155 was correct. 
In the end its because that in COLMAP we use the left convention, while in GTSAM and its reference paper here https://arxiv.org/pdf/1812.01537 the right convention was employed.
This is also in preparation for another PR on propagating relative pose covariance in COLMAP (with left convention) with cross-pose correlation available. This will encode the fact that the close image has lower relative pose covariance and does not get affected by Gauge ambiguity.
=> Add docs on the left convention in COLMAP for covariance propagation.

doc/install.rst, docker/README.md, docker/run-gui.sh
I found that some of my collaborators aren't aware of the pre-built Docker image. I think it would be helpful to mention it somewhere on the documentation's installation page.
=> Add docker instruction link to docs

src/colmap/controllers/incremental_pipeline_test.cc, src/colmap/estimators/absolute_pose.cc, src/colmap/estimators/absolute_pose.h, src/colmap/estimators/absolute_pose_test.cc, src/colmap/estimators/pose.cc, src/colmap/estimators/utils.cc, src/colmap/estimators/utils.h, src/colmap/estimators/utils_test.cc, src/colmap/scene/synthetic.cc, src/colmap/scene/synthetic.h
A/B comparison against main branch. Changes mostly up to numerical noise except for "meadow" as the usual outlier.
```
I20250217 19:45:49.373275 1782301 compare.py:main:58] Results A - B:
=====scenes===== ======AUC @ X deg (%)====== ===images=== =components=
0.5    1.0    5.0    10.0     reg   all  num largest
==============================eth3d=dslr==============================
botanical_garden  -0.03  -0.02  -0.00  -0.00      0     0    0       0
boulders          -0.01  -0.00  -0.00  -0.00      0     0    0       0
bridge             0.00   0.00   0.00   0.00      0     0    0       0
courtyard          0.01   0.00   0.00   0.00      0     0    0       0
delivery_area      0.00   0.00   0.00   0.00      0     0    0       0
door              -0.00  -0.00  -0.00  -0.00      0     0 …
```
=> Compute absolute pose estimation error in image space

.github/workflows/build-ubuntu.yml, src/colmap/estimators/absolute_pose_test.cc, src/colmap/estimators/bundle_adjustment.cc, src/colmap/estimators/bundle_adjustment_test.cc, src/colmap/estimators/cost_functions.h, src/colmap/estimators/pose.cc, src/colmap/image/undistortion.cc, src/colmap/image/warp.cc, src/colmap/mvs/meshing.cc, src/colmap/scene/camera.h, src/colmap/scene/camera_test.cc, src/colmap/scene/image.cc, src/colmap/scene/image.h, src/colmap/scene/image_test.cc, src/colmap/scene/projection.cc, src/colmap/scene/reconstruction_io.cc, src/colmap/scene/synthetic.cc, src/colmap/sensor/models.h, src/colmap/sensor/models_test.cc, src/colmap/ui/point_viewer_widget.cc, src/pycolmap/scene/camera.cc, src/pycolmap/scene/image.cc
Towards supporting spherical / large FOV cameras for which a different logic will have to be implemented than for perspective projection models. The logic is now specialized and localized within the camera model and the user just knows about valid or invalid projections. This can also be used to more robustly deal with numerical issues in distortion computation (as we have for some of the fisheye models).
The next PRs will do the equivalent for CamFromImg to return camera rays rather than image points as well as remove redundant "HasPointPositiveDepth/Cheirality" checks.
=> Camera models perform valid projection test

.github/workflows/build-pycolmap.yml, src/pycolmap/sensor/bitmap.cc
We got hit by the partial python version for the pycolmap CI build again: https://github.com/colmap/colmap/actions/runs/13519440475/job/37775195384
And I just realized that we are always building 3.8 rather than 3.12 on all the pycolmap ci build for pull requests. Was this intended? As it does not align with the comment here: https://github.com/colmap/colmap/blob/main/.github/workflows/build-pycolmap.yml#L35
=> Fix pycolmap ci build for pull requests

pycolmap/generate_stubs.sh, src/pycolmap/main.cc
Following an issue introduced in https://github.com/colmap/colmap/pull/3185, since the type annotation of `QueryOptions.add` depends on `FeatureKeypoint`.
=> Define bindings in the correct order

CMakeLists.txt, src/colmap/estimators/similarity_transform.cc, src/colmap/optim/loransac.h, src/colmap/optim/ransac.h
Fix some code that result in maybe-uninitialized compiler warnings:
- best_model in ransac and loransac can be uninitialized -> use optional,
- initialize Eigen matrices to 0 in EstimateRigid3d and other similar functions.
Also, don't turn the warning type off CMakeLists.txt.
Unfortunately, there are 3 other such warnings that originate outside, namely in boost graph.
=> Fix maybe-uninitialized warnings

.github/workflows/build-ubuntu.yml
The Ubuntu 20.04 Actions runner image will be fully unsupported by 2025-04-01 and temporarily removed on March 4, 11, 18, 25: https://github.com/actions/runner-images/issues/11101
=> Remove Ubuntu 20.04 from the CI

src/colmap/ui/main_window.cc
Without this change, the application crashes when toggling the rendering directly after initialization, because no reconstruction was selected.
=> Fix bug when toggling rendering

src/colmap/scene/synthetic.cc, src/colmap/scene/synthetic.h, src/colmap/scene/synthetic_test.cc
The chained match synthesis was meant to work differently than currently implemented, which would create a separate chain per 3D point track. This PR creates a consistent chain across all tracks leading to sufficient matches for downstream tests. Noticed the issue while observing non-deterministic behavior in our e2e pipeline tests depending on order of tests.
=> Fix chained match synthesis

src/colmap/estimators/alignment.cc, src/colmap/scene/reconstruction.cc, src/colmap/scene/reconstruction.h, src/colmap/scene/reconstruction_io.cc, src/colmap/scene/reconstruction_test.cc, src/pycolmap/scene/reconstruction.cc
The two are semantically identical. The registered_image_ids set only exists for efficiently iterating over the set of registered images.
=> Retire Reconstruction::IsImageRegistered in favor of existing Image::HasPose

src/colmap/estimators/generalized_pose_test.cc, src/colmap/estimators/two_view_geometry.cc, src/colmap/estimators/two_view_geometry_test.cc, src/colmap/geometry/homography_matrix.cc, src/colmap/geometry/homography_matrix_test.cc, src/colmap/geometry/triangulation.cc, src/colmap/geometry/triangulation_test.cc, src/colmap/math/math.h, src/colmap/math/math_test.cc, src/colmap/math/random.h, src/colmap/scene/synthetic.cc
Fixing the unrelated issue of correctly initializing the PRNG in our synthetic scene generator revealed issues with homography pose estimation. Out of the 4 decomposed solutions, the cheirality check can only eliminate 2 and we would randomly pick one of them. I added a reprojection check to resolve the ambiguity. This PR addresses both issues jointly. Previously, on synthetically generated image pairs, half of the pairs would fail to correctly estimate the relative pose from the homography. Now, we achieve 100% success rate. I also added more test coverage.
=> Fix two-view geometry pose estimation for homography

.github/workflows/build-pycolmap.yml
This PR only integrates the python custom pipeline into the CI, to catch relevant issues (typically broken interfaces). We could make the tests more structured once we want to add more coverage on the python side.
=> Add pytest on the e2e python pipeline into CI.

src/colmap/exe/sfm.cc, src/colmap/scene/reconstruction.cc, src/colmap/scene/rig.cc, src/colmap/scene/rig_test.cc
Uses new rig/frame functionality to implement support for the existing rig bundle adjuster functionality. This should be fully backwards compatible. In a follow-up PR, I will delete all code related to legacy rig support (CameraRig struct, RigBundleAdjuster, etc.).
=> Rig bundle adjuster uses default bundle adjustment routine

doc/rigs.rst, python/examples/panorama_sfm.py
Works like a charm on the datasets given in https://github.com/json87/SphereSfM.
What can be improved:
- make `render_perspective_images` faster (currently 1-2s per pano) by moving the logic to C++ (though cv2.remap is already multi-threaded).
- We could create a new CLI steps that outputs a rig_config.json to be consumed after feature extraction by the `rig_configurator` (unfortunately this can't be done in a single step).
- add an option to make feature matching ignore pairs between images of the same frame (since we know here that they are not covisible)
- geometric verification with rig constraints (I have a quick prototype based on PoseLib, for another PR)
=> Add an example script for SfM with 360 spherical images

src/colmap/estimators/pose_test.cc
Hopefully protects us from recent bug in the focal length estimation logic.
=> Add unit test for EstimateAbsolutePose

src/colmap/estimators/generalized_pose_test.cc, src/colmap/estimators/pose_test.cc
* Consistent naming and structure.
* Use of new Rigid3d gmock matcher in generalized pose tests.
=> Cosmetic cleanup for absolute pose tests

src/colmap/estimators/absolute_pose_test.cc, src/colmap/scene/camera.h
The ComputeSquaredReprojectionError test failed in debug mode, because the pinhole model has 2 focal length parameters.
=> Turn camera parameter access debug checks into throwing checks

python/examples/panorama_sfm.py
When running `panorama_sfm.py` with sequential matching, an error occurs because `match_sequential()` expects `sift_options` as the second argument, but receives a `SequentialMatchingOptions` object instead, resulting in a runtime error:
```
TypeError: match_sequential(): incompatible function arguments. The following argument types are supported:
1. (database_path: str, sift_options: pycolmap._core.SiftMatchingOptions = SiftMatchingOptions(), matching_options: pycolmap._core.SequentialMatchingOptions = SequentialMatchingOptions(), verification_options: pycolmap._core.TwoViewGeometryOptions = TwoViewGeometryOptions(), device: pycolmap._core.Device = Device.auto) -> None
Invoked with: PosixPath('sfm/database.db'), SequentialMatchingOptions(overlap=10, quadratic_overlap=True, …
```
=> Fix runtime error in panorama_sfm.py with sequential matching

src/colmap/controllers/feature_matching.cc
The switch to faiss revealed a rare deadlock that can occur when simultaneously reading from the feature matching cache while acquiring the database transaction. This was reliably reproducible with a debugger. Removing the transaction leads to minor performance degradation when writing to the database.
=> Fix deadlock during feature matching

src/colmap/scene/database_cache.cc, src/colmap/scene/database_cache.h
This can avoid code duplication when COLMAP is used as a third party.
=> expose loading database into database cache from DatabaseCache::Create.

src/colmap/scene/database.cc
More safely ensures the statements are reset even if an exception or early return happens before the end of the scope.
=> Introduce context manager to reset sqlite3 statements

doc/index.rst, doc/legacy.rst
Dependent on https://github.com/colmap/colmap.github.io/pull/14
=> Add legacy docs from 3.8 to 3.11.

src/colmap/controllers/incremental_pipeline.cc
Otherwise ``FindNextImages`` will return empty and the process will save a reconstruction with only two frames: https://github.com/colmap/colmap/blob/main/src/colmap/controllers/incremental_pipeline.cc#L575
=> Return bad initial pair when number of triangulation is less than abs_pose_min_num_inliers

docker/run.sh, docker/setup-ubuntu.sh
current setup-ubuntu.sh doen't work becasue cuda10.2 image is no more existed in docker.
So I fixed it.
Confirm I can run 
```
./setup-ubuntu.sh
./run.sh dataset/
```
and run automatic_reconstructor works well inside the docker.
=> Fix setup_ubuntu.sh for docker

src/colmap/math/random.h, src/colmap/util/CMakeLists.txt, src/colmap/util/glog_macros.h, src/colmap/util/logging.h
Older glog versions do not have these macros defined, which leads to a compilation error.
=> Redefine glog's branch prediction macros

.gitignore, src/colmap/controllers/option_manager.cc, src/colmap/feature/pairing.cc, src/colmap/feature/pairing.h, src/colmap/feature/pairing_test.cc, src/colmap/ui/feature_matching_widget.cc, src/pycolmap/pipeline/match_features.cc
This PR adds a `min_num_neighbors` option to `spatial_matcher`, ensuring that each image is matched with at least the specified number of neighbors. This makes matching more adaptive to different image distributions and removes the need to manually tune `max_distance` in some cases.
- Adds `min_num_neighbors` to `SpatialMatchingOptions`. When set to a positive value, the matcher will always include at least that number of neighbors, even if some exceed max_distance
- Adds `CMakeUserPresets.json` and `.clangd` to `.gitignore`
=> Add min_num_neighbors constraint for spatial matching

cmake/FindDependencies.cmake, src/thirdparty/CMakeLists.txt
CMake 3.31 adds support for finding CUDA OpenMP. We do not use this component and it breaks the build if not installed correctly. The same patch was applied in faiss.
=> Only find C/CXX OpenMP components

src/colmap/scene/CMakeLists.txt, src/colmap/scene/database.cc, src/colmap/scene/database.h, src/colmap/scene/database_test.cc, src/colmap/util/CMakeLists.txt, src/colmap/util/string.cc, src/colmap/util/string.h, src/colmap/util/string_test.cc
`sqlite3_open_v2` only accepts UTF-8 encoded paths. This PR adds a function to convert ANSI (platform) strings to UTF-8 on Windows to correctly handle paths containing non-ASCII characters.
=> Ensure UTF-8 encoding for database paths passed to SQLite open

src/colmap/estimators/bundle_adjustment.cc, src/colmap/estimators/covariance_test.cc
This PR fixes SetConstantRigFromWorldPose and corrects the call to SetConstantRigFromWorldPose.
=> Fix BundleAdjustmentConfig::SetConstantRigFromWorldPose

.gitignore
Avoid accidentally checking in compile commands database when configuring the project with `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON`.
=> Ignore compile_commands.json in git

src/colmap/controllers/bundle_adjustment.cc, src/colmap/estimators/bundle_adjustment.cc, src/colmap/sfm/incremental_mapper.cc
Based on reported issue https://github.com/colmap/colmap/issues/3479, I root-caused a performance regression in bundle adjustment to different gauge fixing behavior. In particular, the change from fixing the gauge with two cameras vs. fixing it with three points causes a ~40% slowdown in global bundle adjustment. No significant difference can be measured in local bundle adjustment. I could also not find a significant difference in the obtained solution quality. This PR reverts back to using two cameras for fixing the gauge. If no such two cameras can be found, which can occasionally happen in case of configured non-trivial rigs, we fall back to fixing three points.
=> Fix bundle adjustment performance regression due to changed Gauge

src/colmap/ui/model_viewer_widget.cc
This PR fixs ModelViewerWidget.
This bug can be reproduced by following the steps:
1. Import model by Colmap gui.
2. Double click a image  of the model to view the information of the image.
3. Close the dialog of image information.
4. Import another model.
5. Colmap gui crashed.
`E20250809 00:49:34.254333 19348 image.h:265] 'frame_ptr_' Must be non NULL`
=> Fix ModelViewerWidget::ClearReconstruction

cmake/FindDependencies.cmake
In the upcoming Boost 1.89.0 release, the Boost.System stub library introduced back in 1.69[^1] has been removed (https://github.com/boostorg/system/commit/7a495bb46d7ccd808e4be2a6589260839b0fd3a3), which causes a CMake error.
This PR change using OPTIONAL_COMPONENTS is based on upstream comment `https://github.com/boostorg/system/issues/132#issuecomment-3146378680` given that no minimum Boost is mentioned for project.
[^1]: https://www.boost.org/doc/libs/1_69_0/libs/system/doc/html/system.html#changes_in_boost_1_69
=> Fix build with Boost 1.89.0

cmake/FindDependencies.cmake, python/examples/custom_incremental_pipeline.py, src/pycolmap/scene/database.cc
* Add missing num_rigs/num_frames methods.
* Change to method instead of properties, as the underlying operation is not a trivial readout of a field. This is to make it consistent with the reconstruction object and was unintuitive before. This breaks backwards compatibility but is an easy one to fix.
=> Update database bindings

src/colmap/scene/frame.h
To align with ``Image::SetCameraId`` and ``Image::SetFrameId``.
=> Throw exception for Frame::SetRigId when rig pointer is available.

src/colmap/controllers/feature_matching_utils.cc, src/colmap/feature/sift.cc
1.  **Removed Global Serialization Lock for CUDA**
*   Eliminated `sift_match_gpu_mutexes_` that blocked all CUDA matching operations
*   CUDA version now runs completely lock-free during compute operations
2.  **Explicit CUDA Initialization in Worker Thread Level using `cudaSetDevice()`**
*   Each worker thread initializes its own CUDA context independently
*   Eliminates need for complex per-instance initialization logic
3. **Improved Variable Naming for Clarity**
*   Renamed `sift_match_gpu_mutexes_` to `sift_opengl_mutexes_`
*   Updated comments to clarify OpenGL-specific mutex usage
*   Removed misleading references to "all GPU implementations"
*   **CUDA Context Lifecycle**: CUDA context lifecycle is automatically managed by the driver layer, allowing multiple threads to safely and …
=> Removing the Global Lock in SiftGPUFeatureMatcher for CUDA backend

src/colmap/controllers/option_manager.h
Limit floating-point default values in CLI display to 3 significant digits using StringPrintf("%.3g").
Example changes:  
- `--Mapper.min_focal_length_ratio (=0.10000000000000001)`   ->   `--Mapper.min_focal_length_ratio (=0.1) `
- `--Mapper.init_max_forward_motion (=0.94999999999999996)`  -> `--Mapper.init_max_forward_motion (=0.95) `
- `--SiftExtraction.dsp_min_scale arg (=0.16666666666666666)`  ->  `--SiftExtraction.dsp_min_scale arg (=0.167)`
- `--Example.large_number arg (=500000)`  ->  `--Example.large_number arg (=5e+05)`
- `--Example.small_number arg (=0.00005)`  ->  `--Example.small_number arg (=5e-05)`
=> Display CLI floating-point defaults with 3 significant digits

src/colmap/controllers/feature_matching_utils.cc, src/colmap/feature/matcher.cc
This PR fixs the bug of using skip_image_pairs_in_same_frame=true
```
// Avoid self-matches within a frame.
if (matching_options_.skip_image_pairs_in_same_frame) {
const Image& image1 = cache_->GetImage(image_id1);
const Image& image2 = cache_->GetImage(image_id2);
if (image1.FrameId() == image2.FrameId()) {
continue;
}
}
```
The image's frame ID is not set in MaybeLoadImages. The default value for all images is the same, causing all pairs to be skipped.
Solution:
1. Set the image's frame ID in MaybeLoadImages.
2. Check the validity of the image's frame ID before comparing.
=> Fix MaybeLoadImages

src/pycolmap/scene/frame.cc, src/pycolmap/sensor/rig.cc
This is a crucial fix. Without this the python side problem construction with pyceres will never work. Broken since the rig abstraction in colmap 3.12. 
Equivalent reference in ``image.cam_from_world`` from COLMAP 3.11: https://github.com/colmap/colmap/blob/release/3.11/src/pycolmap/scene/image.cc#L81-L87
To reproduce:
```
import pycolmap
recon = pycolmap.Reconstruction("example/sfm/0")
rig_from_world_1 = recon.frames[1].rig_from_world
rig_from_world_2 = recon.frames[1].rig_from_world
print(id(rig_from_world_1))
print(id(rig_from_world_2))
assert(id(rig_from_world_1) == id(rig_from_world_2))
```
The assertion fails without this fix.
=> rig_from_world and sensor_from_rig in pycolmap should return reference rather than copy.

src/colmap/controllers/incremental_pipeline.cc, src/colmap/controllers/incremental_pipeline.h, src/colmap/controllers/option_manager.cc, src/colmap/sfm/incremental_mapper.cc, src/colmap/sfm/incremental_mapper.h, src/colmap/sfm/incremental_mapper_impl.cc, src/colmap/ui/reconstruction_options_widget.cc, src/pycolmap/sfm/incremental_mapper.cc
* Fixes redundant definition of local_ba_num_images option.
* Renames local_ba_* options to ba_local_* for consistency with all other ba_local/ba_global options.
=> Consistently name local BA options and deduplicate local_ba_num_images
