src/base/camera_models.h

This updates the comment to the changes in commit f69dc8744bba9388c7698e1acf26f4b9005251aa

Update a comment in camera_models.h

---

src/retrieval/vote_and_verify.cc

fix counter matrix of effective inlier

fix counter matrix of effective inlier

---

README.md

Using links with repology and debian packaging

Update on the README.md on binary distributions not for mac/windows

---

src/optim/loransac.h

Refer to #401 for more discussions.

fix issue of finding best local model for loransac

---

scripts/python/export_to_visualsfm.py

This PR enables exporting the descriptors to the binary file format used by Visual SfM.

Binary descriptors export in export_to_visualsfm.py

---

doc/faq.rst

Added detailed instruction how to prepare data properly for recon with known camera poses for newbies (including myself).

updated readme file for recon from known camera poses.

---

scripts/python/test_read_model.py

This is a really minor fix but I might as well make you aware of it. Huge thanks Johannes!

fix compare_points

---

src/controllers/automatic_reconstruction.cc
src/controllers/automatic_reconstruction.h
src/exe/colmap.cc
src/ui/automatic_reconstruction_widget.cc

Hi @ahojnnes 
Everything is in the title. It's just a cleaned up of the patch I send here : https://github.com/colmap/colmap/issues/208#issuecomment-515121435
and sent as a proper pull request. Let me know if any issues
Cheers,
Geoffrey.

automatic_reconstruction : gui and command line support for mask_path

---

src/mvs/gpu_mat.h

In the COLMAP MVS code, the current implementation of `GpuMat::FillWithScalar()` does not properly handle `GpuMat` objects containing multi-byte values. So, this usage of the method:
https://github.com/colmap/colmap/blob/f3d7aae3fd287546edac68d346592175a28f892e/src/mvs/patch_match_cuda.cu#L1633-L1635
does not work as intended, since the `GpuMat<float>` 4-byte matrix values cannot be set by simply calling `cudaMemset()`, which only sets single byte values. Additionally, the method does not properly take the pitch of the `GpuMat` into account.
This pull request fixes these bugs in `GpuMat::FillWithScalar()` by calling a kernel to set the matrix values rather than trying to use `cudaMemset()`.

Fix bug in GpuMat::FillWithScalar() implementation

---

scripts/python/read_write_model.py
scripts/python/test_read_write_model.py

This commit adds functions to write models using python, be it binary of textual
Tests have been added too
Both have been renamed for their new functionality

Add write_model functions for python scripts

---

doc/cameras.rst

I think it is useful to clarify a bit how these two differ. I know camera_models.h explains it, but it looks easier to just spell it out. It also addresses the question in https://github.com/colmap/colmap/issues/121.

Clarify pinhole vs simple pinhole

---

scripts/python/build.py

Paths when building freeimage are incorrect, they have been fixed in this pull request

Fix build.py build_freeimage function

---

src/util/option_manager.cc
src/util/option_manager.h

Fixed unrecognized option random_seed

---

src/util/option_manager.cc

https://github.com/colmap/colmap/issues/903

Enable AddLogOptions in option_manager

---

src/base/homography_matrix.cc
src/base/homography_matrix_test.cc

DecomposeHomographyMatrix() sometimes returns reflection matrices instead of rotations. 
This results in invalid quaternions in two view geometry estimation:
https://github.com/colmap/colmap/blob/91795d028736031901f2fdb1d2cd77956cddd0fc/src/estimators/two_view_geometry.cc#L209
Adding a fix here which just involves making sure the homography matrix has positive determinant before applying the formulas from the paper.
Also added a unit test, and confirmed it fails about half the time without this change.

Ensure DecomposeHomographyMatrix() always returns rotations

---

src/mvs/patch_match.cc

search src images for patch_match from all set, not only referenced subset

---

scripts/python/bundler_to_ply.py
scripts/python/crawl_camera_specs.py
scripts/python/export_to_bundler.py
scripts/python/export_to_visualsfm.py
scripts/python/flickr_downloader.py
scripts/python/merge_ply_files.py
scripts/python/nvm_to_ply.py

Python 3 would not accept print statements without braces

Update print statements for Python 3 compatibility

---

src/base/image.h

More reasonable use point2D_t instead of image_t

use type point2D_t instead of image_t

---

scripts/python/flickr_downloader.py

Prior to this change, all downloaded files will be saved with a .jpg extension, regardless of the actual file type or extension of the file. This change retains the extension of the file.

Modifying scripts/python/flickr_downloader.py to create files with correct extensions

---

src/base/gps.cc
src/base/gps_test.cc

Fix wrong WGS84 model and test cases in GPSTransform

Fix wrong WGS84 model and test cases in GPSTransform

---

CMakeLists.txt

Increase version number to 3.8

---

doc/faq.rst

Updated documentation to match current state of the model_aligner function.

Updating geo-registration doc.

---

src/controllers/incremental_mapper.cc

Fix bug in the computation of the statistics for Global/Local BA.
The bug is reported in #1447

Fix bug in the computation of the statistics Global/Local BA

---

docker/Dockerfile

```log
Please set them or make sure they are set and tested correctly in the CMake files:
METIS_INCLUDE_DIRS
```
https://github.com/colmap/colmap/issues/1451#issuecomment-1062720119

add `libmetis-dev` to solve `METIS_INCLUDE_DIRS`.

---

scripts/python/build.py

Update freeimage links.
Another link issue that has been fixed in #1658.

Update freeimage links.

---

scripts/python/build.py

Update build.py with new glew link

---

doc/faq.rst

Added information about 'camera_mask_path.

Updated faq.rst

---

CMakeLists.txt
src/mvs/cuda_array_wrapper.h
src/mvs/cuda_texture.h
src/mvs/gpu_mat_ref_image.cu
src/mvs/gpu_mat_ref_image.h
src/mvs/patch_match_cuda.cu
src/mvs/patch_match_cuda.h

One step towards supporting Cuda 12+.

Replace deprecated Cuda texture references with texture objects

---

lib/SiftGPU/CuTexImage.cpp
lib/SiftGPU/CuTexImage.h
lib/SiftGPU/ProgramCU.cu
lib/SiftGPU/PyramidCU.cpp

Another step towards CUDA 12 support.

Upgrade SiftGPU to use CUDA texture objects

---

src/colmap/base/alignment.cc
src/colmap/base/alignment.h
src/colmap/base/reconstruction.cc
src/colmap/base/reconstruction.h
src/colmap/base/reconstruction_test.cc
src/colmap/controllers/hierarchical_mapper_test.cc
src/colmap/controllers/incremental_mapper_test.cc
src/colmap/estimators/absolute_pose_test.cc
src/colmap/estimators/coordinate_frame.cc
src/colmap/estimators/coordinate_frame.h
src/colmap/estimators/coordinate_frame_test.cc
src/colmap/estimators/euclidean_transform.h
src/colmap/estimators/generalized_absolute_pose_test.cc
src/colmap/estimators/generalized_relative_pose_test.cc
src/colmap/exe/model.cc
src/colmap/geometry/CMakeLists.txt
src/colmap/geometry/sim3.cc
src/colmap/geometry/sim3.h
src/colmap/geometry/sim3_test.cc
src/colmap/geometry/triangulation_test.cc
src/colmap/optim/loransac_test.cc
src/colmap/optim/ransac_test.cc

In preparation for rigid3d class.

Rename SimilarityTransform3 to Sim3d

---

src/colmap/base/camera.cc
src/colmap/base/cost_functions.h
src/colmap/camera/models.h
src/colmap/camera/models_test.cc

First step towards supporting spherical camera models. Next up is supporting camera rays in geometry modules like triangulation, etc.

Camera models operate on camera rays

---

doc/install.rst

Removed in https://github.com/colmap/colmap/commit/f5798700fd115f4a03f824a00744748b3270ba18

Remove mention of deprecated build script

---

doc/cameras.rst

Fixes link to source code to correct path in the restructured code.

Update cameras.rst to fix link to code

---

src/colmap/estimators/cost_functions.h
src/colmap/estimators/cost_functions_test.cc

I will add pycolmap bindings in a future PR

Add costs for pose graph optimization

---

src/colmap/util/logging.h

Glog 0.7.0 was released yesterday.

Fix for glog 0.7.0

---

src/pycolmap/estimators/two_view_geometry.cc
src/pycolmap/scene/correspondence_graph.cc
src/pycolmap/utils.h

Superseeds and closes PR https://github.com/colmap/colmap/pull/2458

Improve bindings of CorrespondenceGraph

---

src/colmap/scene/reconstruction.cc
src/colmap/scene/reconstruction.h
src/pycolmap/scene/image.cc
src/pycolmap/scene/reconstruction.cc

Superseeds and closes PR https://github.com/colmap/colmap/pull/2474

Bind Reconstruction::{SetUp,ImagePairStats}

---

pycolmap/custom_bundle_adjustment.py

Fix python bundle adjustment example with pyceres

---

src/colmap/math/polynomial.cc
src/colmap/math/polynomial.h
src/colmap/math/polynomial_test.cc

To be used by faster 7-point solver.

Add function to find real cubic polynomial roots

---

src/colmap/estimators/fundamental_matrix.cc
src/colmap/estimators/fundamental_matrix_test.cc

The new implementation is ~4x faster and a little more often produces a valid model.

Faster 7-point fundamental matrix estimator

---

README.md
doc/install.rst

- Updated documentation about compiling on arm.
- Removed mention of Mac OS on prebuilt binaries as they are not supported any more (https://github.com/colmap/colmap/discussions/2560#discussioncomment-9404683)

Mac OS improvements

---

src/colmap/geometry/essential_matrix.cc

This aligns the implementation of FindOptimalImageObservations() with the algorithm listing 'niter2' from the paper 'Triangulation Made Easy' by P. Lindstrom [1].
[1] Lindstrom, Peter. (2010). Triangulation Made Easy. Proceedings / CVPR, IEEE Computer Society Conference on Computer Vision and Pattern Recognition. IEEE Computer Society Conference on Computer Vision and Pattern Recognition. 1554-1561. 10.1109/CVPR.2010.5539785.

Fix optimal point algorithm

---

doc/faq.rst
src/colmap/exe/model.cc

Fix: https://github.com/colmap/colmap/issues/2695

Remove non existant flags of model_aligner from docs

---

src/colmap/math/math.cc
src/colmap/math/math.h
src/colmap/math/math_test.cc

Improved implementation that can handle larger values of n and k without overflowing.

Robustify nchoosek against overflow

---

scripts/python/database.py

As pointed out by @sephyli in https://github.com/colmap/colmap/pull/2620

Remove pose prior from database.py:add_image

---

pycolmap/custom_incremental_mapping.py
src/colmap/controllers/automatic_reconstruction.cc
src/colmap/controllers/hierarchical_mapper.cc
src/colmap/controllers/hierarchical_mapper.h
src/colmap/controllers/incremental_mapper.cc
src/colmap/controllers/incremental_mapper.h
src/colmap/controllers/incremental_mapper_test.cc
src/colmap/controllers/option_manager.cc
src/colmap/controllers/option_manager.h
src/colmap/exe/sfm.cc
src/colmap/exe/sfm.h
src/colmap/ui/main_window.cc
src/colmap/ui/main_window.h
src/pycolmap/pipeline/sfm.cc
src/pycolmap/sfm/incremental_mapper.cc

As raised here: https://github.com/colmap/colmap/issues/2648
Not sure how much downstream code this renaming will break though. Just opened this PR in case we want to proceed with it.

Rename IncrementalMapperOptions to IncrementalPipelineOptions

---

src/colmap/controllers/hierarchical_mapper.cc
src/colmap/controllers/hierarchical_mapper.h
src/colmap/controllers/hierarchical_mapper_test.cc
src/colmap/exe/sfm.cc

For consistency with new IncrementalPipeline name.

Rename HierarchicalMapperController to HierarchicalPipeline

---

doc/_static/custom.css
doc/conf.py
doc/index.rst
doc/pycolmap/api.rst
doc/pycolmap/cost_functions.rst
doc/pycolmap/index.rst
doc/requirements.txt
src/pycolmap/estimators/bundle_adjustment.cc
src/pycolmap/geometry/bindings.cc
src/pycolmap/main.cc
src/pycolmap/scene/reconstruction.cc
src/pycolmap/scene/track.cc
src/pycolmap/sfm/observation_manager.cc

Build result: https://github.com/colmap/colmap.github.io/pull/8
The API list is pretty long, so I will break it down into different modules (estimators, scene, etc.) in a subsequent PR.

PyCOLMAP API documentation

---

src/pycolmap/geometry/bindings.cc
src/pycolmap/sfm/incremental_triangulator.cc

https://github.com/colmap/colmap/pull/2752 got merged too early.

Follow-up fixes in pycolmap

---

src/colmap/scene/reconstruction.cc
src/colmap/scene/reconstruction.h
src/colmap/scene/reconstruction_test.cc
src/colmap/sfm/incremental_mapper.cc

Addresses https://github.com/colmap/colmap/issues/2775. Missed from https://github.com/colmap/colmap/pull/2762

Fix missing camera ptr for Reconstruction.DeleteAllPoints2DAndPoints3D()

---

src/colmap/estimators/bundle_adjustment.cc
src/colmap/exe/image.cc
src/colmap/scene/database_cache.cc
src/colmap/sfm/incremental_mapper.cc
src/colmap/sfm/observation_manager.cc

Now that we upgraded to C++17, we can use some nice new features that make the code more readable. Made a small pass over the code and added usage of structured bindings. This is not meant to be a complete pass but an effort to raise awareness of this feature.

Use C++17 structured bindings in some places

---

src/colmap/estimators/bundle_adjustment.cc

Fixes https://github.com/colmap/colmap/issues/2817

Fix selection of BA solver type when there is no cuda

---

src/colmap/estimators/pose.cc

No change in behavior, just an incorrect notation. Noticed during related code refactoring.

Fix coordinate notation in EstimateAbsolutePose

---

src/colmap/controllers/automatic_reconstruction.cc

Fixes reported issue: https://github.com/colmap/colmap/discussions/2890

Fix input type for automatic stereo fusion on extreme quality setting

---

src/thirdparty/SiftGPU/CuTexImage.cpp
src/thirdparty/SiftGPU/CuTexImage.h
src/thirdparty/SiftGPU/PyramidCU.cpp

Fixes issue: https://github.com/colmap/colmap/issues/2898

Fix conversion from CUDA texture references to objects in SIFT feature extraction

---

src/colmap/controllers/automatic_reconstruction.h
src/colmap/geometry/gps.h
src/colmap/sensor/models.h
src/colmap/util/CMakeLists.txt
src/colmap/util/enum_to_string.h
src/colmap/util/enum_to_string_test.cc

I adapted only a few for now as examples. If we are happy with it we could apply on all enum classes.

Custom macro for enum to string support

---

src/thirdparty/SiftGPU/CMakeLists.txt
src/thirdparty/SiftGPU/PyramidGL.cpp
src/thirdparty/VLFeat/CMakeLists.txt

The only fix that was required to get colmap working on Windows ARM64.

Fixes for Windows ARM64 support

---

src/colmap/feature/sift.cc
src/colmap/feature/sift_test.cc

Fixes: https://github.com/colmap/colmap/issues/2928

Fix affine SIFT feature orientation detection

---

src/pycolmap/scene/bindings.cc
src/pycolmap/scene/synthetic.cc

In preparation for testing the pycolmap interfaces.

Bind synthetic dataset functionality in pycolmap

---

.github/workflows/build-pycolmap.yml
pycolmap/pycolmap/utils.py

Introduced by https://github.com/colmap/colmap/pull/2933

Fix pycolmap breakage for Python 3.8

---

src/colmap/sensor/bitmap.cc
src/pycolmap/helpers.h

Instead of compiling upon each function invocation, statically compile the regex once upon first call.

Statically compile const regular expressions once

---

pycolmap/examples/example.py

The name ``custom_incremental_mapping.py`` is updated in https://github.com/colmap/colmap/pull/2946

Adapt to the name changes for pycolmap example

---

src/colmap/estimators/bundle_adjustment.cc

Fixes: https://github.com/colmap/colmap/issues/2992

Fix setting of RANSAC max error in pose prior BA alignment

---

.clangd
src/colmap/geometry/gps.cc
src/colmap/geometry/gps.h
src/colmap/geometry/gps_test.cc

- Add feature mentioned in #3017
- Add related unit tests, which have been passed on my machine.

Add conversion between LLA and UTM coords.

---

.github/workflows/build-windows.yml
CMakeLists.txt
pycolmap/ci/install-colmap-almalinux.sh
pycolmap/pyproject.toml
vcpkg.json

Makes it easier to keep the two in sync in the future. Includes Ceres 2.2 update.

Set vcpkg default features and synchronize to latest vcpkg

---

src/colmap/sfm/incremental_mapper.cc

Minor update concerning the dependencies described in https://github.com/colmap/colmap/pull/3043

Reorder destructors for better safety in EndReconstruction

---

src/colmap/util/file.cc
src/colmap/util/file.h

Fix compilation with DOWNLOAD_ENABLED=OFF

---

src/colmap/exe/colmap.cc
src/colmap/ui/main_window.cc

The resources are unused by anything other than the UI library.

Init Qt UI resources in UI library

---

src/colmap/sfm/incremental_triangulator.cc

We need some tests for this class, however, this is out of scope for this bugfix PR. It will be a more significant effort to implement these.

Fix transitive completion in incremental triangulator

---

src/colmap/ui/model_viewer_widget.cc
src/colmap/ui/point_viewer_widget.cc

Fixes: https://github.com/colmap/colmap/issues/3096

Fix image deletion, hide point viewer widget after deletion

---

src/colmap/controllers/incremental_pipeline.h
src/pycolmap/sfm/incremental_mapper.cc

Fixes: https://github.com/colmap/colmap/issues/3101

Expose incremental mapper pose prior options in pycolmap

---

src/colmap/estimators/covariance.cc
src/colmap/estimators/covariance.h
src/colmap/estimators/covariance_test.cc
src/pycolmap/estimators/covariance.cc

Now the name is too long. Creating this PR to initiate the thread.

Fix naming of cross covariance and add relative pose covariance interface

---

python/incremental_build.sh

With recent move of pyproject.toml to the root folder, the script needs an update.

Fix incremental pycolmap build script

---

src/colmap/controllers/image_reader.h

No change other than regrouping of the options for better readability.

Logically group image reader options

---

python/incremental_build.sh
src/colmap/controllers/image_reader.h
src/colmap/estimators/alignment.cc
src/colmap/estimators/generalized_pose_test.cc
src/colmap/estimators/two_view_geometry.cc
src/colmap/estimators/two_view_geometry_test.cc
src/colmap/geometry/homography_matrix.cc
src/colmap/geometry/homography_matrix_test.cc
src/colmap/geometry/triangulation.cc
src/colmap/geometry/triangulation_test.cc
src/colmap/math/math.h
src/colmap/math/math_test.cc
src/colmap/math/random.h
src/colmap/scene/reconstruction.cc
src/colmap/scene/reconstruction.h
src/colmap/scene/reconstruction_io.cc
src/colmap/scene/reconstruction_test.cc
src/colmap/scene/synthetic.cc
src/colmap/scene/synthetic.h
src/colmap/scene/synthetic_test.cc
src/colmap/sensor/models_test.cc
src/colmap/util/CMakeLists.txt
src/pycolmap/scene/reconstruction.cc

To make it easier to review already merged changes into main from the open rig PR.

Pull latest changes from main to feature/rig

---

src/colmap/controllers/option_manager.cc
src/colmap/feature/matcher.cc
src/colmap/feature/matcher.h
src/colmap/feature/pairing.cc
src/colmap/feature/pairing.h
src/colmap/feature/pairing_test.cc
src/colmap/scene/synthetic.cc
src/colmap/scene/synthetic_test.cc
src/pycolmap/pipeline/match_features.cc

This is useful for matching a sequential rig dataset.

Sequential matcher expands rig images

---

.github/workflows/build-windows.yml
pyproject.toml

Includes the following important fixes: https://github.com/microsoft/vcpkg/pull/43912

Update vcpkg to pull in fixes for ceres

---

src/pycolmap/pipeline/match_features.cc

Fixes https://github.com/colmap/colmap/issues/3298

Bind missing SequentialMatchingOptions.loop_detection_period

---

src/colmap/geometry/homography_matrix_test.cc

Other prng standard library implementations can produce poses where all points are behind the camera, which leads to a test failure.

Deterministic homography test

---

src/colmap/util/cache.h

Now that we use C++17, we can use shared locks.

Use shared lock in thread safe LRU cache

---

doc/concepts.rst
doc/conf.py
doc/database.rst
doc/index.rst

Initiating this. Adding the missing definitions of rigs and frames in the docs.  Feel free to update as you wish : )

Add docs to explain the concepts of rigs and frames.

---

src/colmap/controllers/incremental_pipeline_test.cc
src/colmap/sfm/incremental_mapper.cc

Alternative fix for the following issue: https://github.com/colmap/colmap/pull/3158

Do not filter existing, fixed frames

---

src/colmap/exe/sfm.cc

Also do not crash on Ceres failure, as the regular BA does not do so.

Add deprecation warning for rig_bundle_adjuster

---

docker/Dockerfile

Fixes https://github.com/colmap/colmap/issues/3444

Add missing libraries to docker runtime

---

docker/run-gui.sh
docker/run.sh

Fix that docker/run-gui.sh doesn't work issue.
Originally docker/run-gui.sh doesn't start because of Nvidia driver issue.
So I followed as docker/run.sh fixation, fix run-gui.sh also work with locally built docker image.
At the same time, I encountered my dual monitor window freezing issue.
So I fixed it adding several options to run docker run command.
I checked that both run.sh and run-gui.sh invokes fine, and run-gui.sh can successfully load colmap reconstructed model like this;

Fix docker run script for GUI

---

src/colmap/controllers/feature_matching_utils.cc
src/colmap/feature/pairing.cc
src/colmap/scene/correspondence_graph.cc
src/colmap/scene/correspondence_graph.h
src/colmap/scene/correspondence_graph_test.cc
src/colmap/scene/database.cc
src/colmap/scene/database.h
src/colmap/scene/database_cache.cc
src/colmap/scene/database_test.cc
src/colmap/scene/scene_clustering.cc
src/colmap/scene/synthetic.cc
src/colmap/scene/synthetic_test.cc
src/colmap/sfm/incremental_mapper.cc
src/colmap/sfm/incremental_mapper_impl.cc
src/colmap/sfm/incremental_triangulator.cc
src/colmap/sfm/observation_manager.cc
src/colmap/ui/match_matrix_widget.cc
src/colmap/util/types.h
src/pycolmap/scene/database.cc
src/pycolmap/util/types.cc

Hosting these functions in the database has not made sense for a long while now.

Extract image pair conversion functions into type utils

---

src/colmap/feature/matcher.cc
src/colmap/feature/matcher.h

For some DB implementations, this can be slow.

Cache max number of keypoints

---

.github/workflows/build-mac.yml
doc/cli.rst
doc/faq.rst
python/ci/install-colmap-macos.sh
src/colmap/controllers/feature_extraction.cc
src/colmap/controllers/option_manager.cc
src/colmap/feature/extractor.cc
src/colmap/feature/extractor.h
src/colmap/feature/sift.cc
src/colmap/feature/sift.h
src/colmap/ui/feature_extraction_widget.cc
src/pycolmap/feature/extraction.cc

Towards the introduction of new feature extractors.

Share feature extraction max_image_size option
